QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C. America/Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <inlineHelpText>Either Subscription (ACV and ACV/TRANS) or Project (PROJ).  Required to save the Opportunity.</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Ipreo Vertical with which Opportunity is associated (ex GMG, Corporate).  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Region__c</fullName>
        <inlineHelpText>Defaults from Region of Opportunity Owner.  Can be changed.</inlineHelpText>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Revenue_Type__c</fullName>
        <description>Type of revenue associated with the opportunity product</description>
        <inlineHelpText>ACV:  Annual Contracted Value - subscription product.  PROJ:  Project.  ACV/TRANS:  Usage based product.  ACV/PROJ:  Project sold as part of a subscription.</inlineHelpText>
        <label>Product Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Vertical__c</fullName>
        <label>Product Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_OpportunityProductAssignValueTHander.cls
/**************************************************************************************************
 * Name           : GS_OpportunityProductAssignValueTHander
 * Object         : OpportunityLineItem
 * Requirement    : STY-00045, STY-00171, STY-00011
 * Target         : Assign value when an opportunity product is created
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-16
 * Modify History :
 **************************************************************************************************/
public class GS_OpportunityProductAssignValueTHander implements GS_Triggers.Handler {
	public void handle() {
		if (Trigger.isBefore) {
			System.debug(LoggingLevel.INFO, '*** GS_OpportunityProductAssignValueTHander.');
			System.debug(LoggingLevel.INFO, '*** trigger.new: ' + trigger.new);

			Map<Id, OpportunityLineItem> mapNewLineItems = (Map<Id,OpportunityLineItem>)Trigger.newMap;
			Set<Id> setOppIds = new Set<Id>();
			Set<Id> setProdIds = new Set<Id>();
			Set<Id> setCreatedByIds = new Set<Id>();
			Map<Id, Opportunity> mapOpportunity = new Map<Id, Opportunity>();
			Map<Id, Product2> mapProduct = new Map<Id, Product2>();
			Map<Id, User> mapUser = new Map<Id, User>();

			for(OpportunityLineItem tempLineItem : (List<OpportunityLineItem>)Trigger.new) {
				if(!setOppIds.contains(tempLineItem.OpportunityId)) {
					setOppIds.add(tempLineItem.OpportunityId);
				}

				if(!setProdIds.contains(tempLineItem.Product2Id)) {
					setProdIds.add(tempLineItem.Product2Id);
				}
			}
			setCreatedByIds.add(UserInfo.getUserId());

			if(setOppIds.size() > 0) {
				mapOpportunity = new Map<Id, Opportunity>(GS_OpportunityDMLHandler.getOpportunitiesById(setOppIds));
			}

			if(setProdIds.size() > 0) {
				mapProduct = new Map<Id, Product2>(GS_ProductDMLHandler.getProductsById(setProdIds));
			}

			if(setCreatedByIds.size() > 0) {
				mapUser = new Map<Id, User>(GS_UserDMLHandler.getUsersByIds(setCreatedByIds));
			}

			//Map<Id, OpportunityLineItem> mapNewLineItems = new Map<Id, OpportunityLineItem>(GS_OpportunityDMLHandler.getLineItemsById(Trigger.newMap.keyset()));
			System.debug(LoggingLevel.INFO, '*** mapNewLineItems: ' + mapNewLineItems);
			for(OpportunityLineItem tempLineItem : (List<OpportunityLineItem>)Trigger.new) {

				// Set Product_Region__c
				if (String.isBlank(tempLineItem.Product_Region__c)) {
					//mapNewLineItems.get(tempId).Product_Region__c = mapNewLineItems.get(tempId).CreatedBy.Region__c;
					System.debug(LoggingLevel.INFO, '*** tempLineItem.CreatedById: ' + tempLineItem.CreatedById);
					tempLineItem.Product_Region__c = mapUser.get(UserInfo.getUserId()).Region__c;
				}

				// Set Product_Vertical__c
				if (String.isBlank(tempLineItem.Product_Vertical__c)) {
					//mapNewLineItems.get(tempId).Product_Vertical__c = mapNewLineItems.get(tempId).Opportunity.Account.Vertical__c;
					tempLineItem.Product_Vertical__c = mapProduct.get(tempLineItem.Product2Id).Vertical__c;
				}

				// Set Product_Revenue_Type__c
				if( String.isBlank(tempLineItem.Product_Revenue_Type__c) && !String.isBlank(tempLineItem.Product_Vertical__c)) {
					tempLineItem.Product_Revenue_Type__c = mapProduct.get(tempLineItem.Product2Id).Revenue_Type__c;
				}

				System.debug(LoggingLevel.INFO, '*** tempLineItem.Product_Revenue_Type__c: ' + tempLineItem.Product_Revenue_Type__c);
			}
		}
	}
}