QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Use to show on email template</description>
        <label>Opportunity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ACV__c</fullName>
        <description>Annual Contract Value</description>
        <inlineHelpText>Annual Contracted Value - Roll up of ACpV (Annual Contract Product Value) from Opportunity Product(s).</inlineHelpText>
        <label>ACV</label>
        <summarizedField>OpportunityLineItem.ACpV__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Annual_Pass_Through__c</fullName>
        <inlineHelpText>Roll up of Annual Pass Through from Opportunity Product(s).</inlineHelpText>
        <label>Annual Pass Through</label>
        <summarizedField>OpportunityLineItem.Annual_Pass_Through__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Status__c</field>
            <operation>notEqual</operation>
            <value>Lost</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Estimated_Annual_Transaction_Fees__c</fullName>
        <inlineHelpText>Roll up of Estimated Annual Transaction Fees from Opportunity Product(s).</inlineHelpText>
        <label>Est. Annual Transaction Fees</label>
        <summarizedField>OpportunityLineItem.Estimated_Annual_Fees__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Status__c</field>
            <operation>notEqual</operation>
            <value>Lost</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Net_New_Business__c</fullName>
        <inlineHelpText>Roll up of Net New Business from Opportunity Product(s).  Also (ACV - Annual Pass Through) - (Prior Year ACV - Prior Year Pass Through).</inlineHelpText>
        <label>Net New Business</label>
        <summarizedField>OpportunityLineItem.Net_New_Business__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_GMG_Opportunity_Products__c</fullName>
        <description>Number of GMG Opportunity Products</description>
        <label>No. of GMG Opportunity Products</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.Product_Vertical__c</field>
            <operation>equals</operation>
            <value>GMG</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prior_Year_ACV__c</fullName>
        <inlineHelpText>Roll up of Prior Year ACpV from Opportunity Product(s).</inlineHelpText>
        <label>Prior Year ACV</label>
        <summarizedField>OpportunityLineItem.Prior_Year_ACpV__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Status__c</field>
            <operation>notEqual</operation>
            <value>Lost</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prior_Year_Pass_Through__c</fullName>
        <inlineHelpText>Roll up of Prior Year Pass Through from Opportunity Product(s).</inlineHelpText>
        <label>Prior Year Pass Through</label>
        <summarizedField>OpportunityLineItem.Prior_Year_Pass_Through__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Status__c</field>
            <operation>notEqual</operation>
            <value>Lost</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Ipreo Vertical with which Opportunity is associated (ex GMG, Corporate).  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Opportunity_Pipeline_History__c.object
<CustomObject>
    <fields>
        <fullName>ACV__c</fullName>
        <label>ACV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Pipeline History Records</relationshipLabel>
        <relationshipName>Opportunity_Pipeline_History_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Annual_Transaction_Fees__c</fullName>
        <label>Est. Annual Transaction Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_New_Business__c</fullName>
        <label>Net New Business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Currency__c</fullName>
        <label>Opportunity Currency</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <label>Opportunity Owner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Pipeline_History_Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Opportunity Pipeline History Unique Key</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Pipeline History Records</relationshipLabel>
        <relationshipName>Opportunity_Pipeline_History_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pass_Through__c</fullName>
        <label>Pass Through</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Year_ACV__c</fullName>
        <label>Prior Year ACV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Year_Pass_Through__c</fullName>
        <label>Prior Year Pass Through</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <label>TCV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Pipeline History</label>
    <nameField>
        <displayFormat>OPH-{000000}</displayFormat>
        <label>Opportunity Pipeline History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Pipeline Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_OpportunityPipelineHistoryBatch.cls
global class GS_OpportunityPipelineHistoryBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
	global list<String> toAddresses = new list<String>{'salesforce_notifications@ipreo.com'};
	global integer totalCount = 0;
    global integer failedCount = 0;
    global integer successCount = 0;
    global string failedMessages = '';
	
	global Database.QueryLocator start(Database.BatchableContext bc) {
        string query = 'SELECT AccountId, Account.Name, ACV__c, CloseDate, Estimated_Annual_Transaction_Fees__c, Net_New_Business__c, Id, CurrencyIsoCode, Name, ' +
        					  'OwnerId, Owner.Name, Annual_Pass_Through__c, Prior_Year_ACV__c, Prior_Year_Pass_Through__c, RecordType.Name, StageName, Amount, Vertical__c, ' +
        					  'No_of_GMG_Opportunity_Products__c ' +
					   'FROM Opportunity WHERE isClosed = false';
					   
		if (test.isRunningTest())
			query += ' LIMIT 100';
		
		return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Sobject> scope) {
		System.debug(scope.size());
		
		List<Opportunity_Pipeline_History__c> ophs = new List<Opportunity_Pipeline_History__c>();
		
		for (Opportunity opp : (List<Opportunity>)scope) {
			Opportunity_Pipeline_History__c oph = new Opportunity_Pipeline_History__c();
			
			oph.Account__c = opp.AccountId;
			oph.Account_Name__c = opp.Account.Name;
			oph.ACV__c = opp.ACV__c;
			oph.Close_Date__c = opp.CloseDate;
			oph.Estimated_Annual_Transaction_Fees__c = opp.Estimated_Annual_Transaction_Fees__c;
			oph.Net_New_Business__c = opp.Net_New_Business__c;
			oph.Opportunity__c = opp.Id;
			oph.CurrencyIsoCode = opp.CurrencyIsoCode;
			oph.Opportunity_Currency__c = opp.CurrencyIsoCode;
			oph.Opportunity_Name__c = opp.Name;
			oph.Opportunity_Owner__c = opp.Owner.Name;
			oph.Pass_Through__c = opp.Annual_Pass_Through__c;
			oph.Prior_Year_ACV__c = opp.Prior_Year_ACV__c;
			oph.Prior_Year_Pass_Through__c = opp.Prior_Year_Pass_Through__c;
			oph.Record_Type__c = opp.RecordType.Name;
			oph.Stage__c = opp.StageName;
			oph.TCV__c = opp.Amount;
			oph.Opportunity_Pipeline_History_Unique_Key__c = opp.Id + '_' + System.today().format();
			
			if (opp.No_of_GMG_Opportunity_Products__c > 0)
				oph.Vertical__c = 'GMG';
			else
				oph.Vertical__c = 'Corporate';
			
			ophs.add(oph);
		}
		
		System.debug(ophs.size());
		totalCount += ophs.size();
		
		if (ophs.size() > 0) {
			try {
				upsert ophs Opportunity_Pipeline_History__c.Field.Opportunity_Pipeline_History_Unique_Key__c;
				successCount += ophs.size();
			}
			catch (Exception e) {
				failedCount += ophs.size();
				failedMessages += e.getMessage();
			}
		}
    }

    global void finish(Database.BatchableContext BC) {
		Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
    	
    	email.setToAddresses(toAddresses); 
		email.setSubject('Weekly Opportunity Pipeline History Batch Job Completed');
		string textBody = 'The weekly batch job to capture Opportunity pipeline history has completed. Below is a summary of the results:' +
							'\n\nTotal number of records: ' + totalCount + '\nSuccess: ' + successCount + '\nFailed: '+ failedCount;
        if(failedMessages != '') {
        	textBody += '\n\nError Messages:\n' + failedMessages;
        }
            
        textBody += '\n\nBatch class used in the job: "GS_OpportunityPipelineHistoryBatch"';
            
        email.setPlainTextBody(textBody);
            
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});		
    }
    
	global void execute(SchedulableContext SC) {
		GS_OpportunityPipelineHistoryBatch batchJob = new GS_OpportunityPipelineHistoryBatch();
		Database.executeBatch(batchJob, 200);
	}
}