QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/Contract__c.object
<CustomObject>
    <description>Used instead of the standard Contract object to allow queues.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <inlineHelpText>MSA With Schedules: Master Services Agreement
Data Agreement: change to data access
Project Agreement:  customer consent to purchase Project
Amendment/Schedule:  new schedule assoc with existing MSA
Additional User Agreement:  change to No. of users</inlineHelpText>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSA with Schedules</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment/Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional User Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Form Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_Attachments__c</fullName>
        <description>Used to calculate the number of attachments on the contract, this field will not on the page layout, it&apos;s for validation.</description>
        <label>No. of Attachments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Executed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestAttachmentCalNumberTHandler.cls
@isTest
private class GS_TestAttachmentCalNumberTHandler {
    static testMethod void TestAttachmentCalNumberTHandler() {

    	Account testAccount1 = GS_TestDataCreator.createAccount('TestAccount','Buyside','Tier 1');
        Contract__c testContract = new Contract__c(
        								Name = 'Test Contract',
        								Account__c = testAccount1.Id,
        								Contract_Type__c = 'Renewal',
        								Status__c = 'Pending');
        insert testContract;

        Attachment testAttachment = GS_TestDataCreator.createAttachment(testContract, 'Test Attachment', false, 'Test Attachment Contents');

        List<Contract__c> lstConResult = [select Id,No_of_Attachments__c from Contract__c where Id = :testContract.Id];
        if(lstConResult.size() > 0)
        {
        	System.assertEquals(1, lstConResult[0].No_of_Attachments__c);
        }

        delete testAttachment;
        List<Contract__c> lstConResult2 = [select Id,No_of_Attachments__c from Contract__c where Id = :testContract.Id];
        if(lstConResult2.size() > 0)
        {
        	System.assertEquals(0, lstConResult2[0].No_of_Attachments__c);
        }
    }
}