QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>Est. Completion Date based on Est. Completion Date of Opp Products. This field gets updated using Apex Class</description>
        <label>Opportunity Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>To track Delivery Date on Opportunity Products  when project revenue will be realized.</description>
        <inlineHelpText>Date on which project or report is expected to be delivered.  Applies to Project products, only; n/a for subscription products.  Required at Won or at Renewed if Subscription Dates and Term are not entered.</inlineHelpText>
        <label>Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Revenue_Type__c</fullName>
        <description>Type of revenue associated with the opportunity product</description>
        <inlineHelpText>ACV:  Annual Contracted Value - subscription product.  PROJ:  Project.  ACV/TRANS:  Usage based product.  ACV/PROJ:  Project sold as part of a subscription.</inlineHelpText>
        <label>Product Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The values of Won/Lost pertain to New Business opportunities and the values of Cancelled/Renewed pertain to Renewal opportunities.</description>
        <inlineHelpText>Required when Opportunity Stage is Closed%.  When Status has not been populated, most fields on page are not validated by system.  Once Status is populated (with either Won/Lost for New Business or Renewed/Cancelled for Renewals), the validations occur.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Product_Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Subscription End Date must be same (coterminous) for all Opportunity Products on the Opportunity.  Req at Won, Renewed if Subscription Start Date and Term populated.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Required at Status &apos;Won&apos; or &apos;Renewed&apos; if Subscription End Date and Term are populated.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <description>Opportunity Term in Months</description>
        <inlineHelpText>Term of subscription, INCLUSIVE of any free period.  Leave blank for non-subscription products.  If entered, Subscription Start Date and Subscription End Date must also be entered.</inlineHelpText>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_TestOppLineItemRecordValidation.cls
/**************************************************************************************************
 * Name           : GS_TestOppLineItemRecordValidation
 * Object         : OpportunityLineItem
 * Requirement    : STY-00187
 * Target         : Test GS_OppLineItemRecordValidationTHandler
 * Refer classes  : 
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-06
 * Modify History :
 **************************************************************************************************/
@isTest
private class GS_TestOppLineItemRecordValidation {

	// IF Status IN ( "Won", "Renewed" ) AND Subscription End Date ≠ null AND Subscription End Date ≠ one or more Subscription End Dates on Opportunity Products 
	// related to the same opportunity, THEN error:  "All subscription end dates must be coterminous"
	static testMethod void recordValidation() {

		Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
    	Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
    	testSetting1.Name = 'Opportunity';
    	testSetting2.Name = 'OpportunityTeam';
    	testSetting1.isOpen__c = true;
    	testSetting2.isOpen__c = true;
    	insert testSetting1;	
    	insert testSetting2;

		Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
		Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
		
		// createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
		Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true);
		Product2 testProduct2 = GS_TestDataCreator.createProduct('TestProduct2', true, false);

		// createPriceBookEntry(Product2 product, Decimal unitPrice)
		PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);
		PricebookEntry testPBEntry2 = GS_TestDataCreator.createPriceBookEntry(testProduct2, 100);

		// createOppLineItem(PricebookEntry priceEntry, Opportunity opp, String productTransactionType, Decimal acpv, Decimal tcpv, Decimal passThrough)
		OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp, 'New Business', 100, 200, 50, 'Yes', 'Analec', null, null, null, 'ACV', 'NA');	
		OpportunityLineItem oppLineItem2 = GS_TestDataCreator.createOppLineItem(testPBEntry2, testOpp, 'New Business', 50, 100, null, 'Yes', 'Analec', null, null, null, 'ACV', 'NA');
		
		List<OpportunityLineItem> lstTestOppLineItems = new List<OpportunityLineItem>();

		oppLineItem1.Status__c = 'Won';
		oppLineItem1.Subscription_Start_Date__c = Date.valueOf('2015-09-07');
		oppLineItem1.Subscription_End_Date__c = Date.valueOf('2015-09-30');
		oppLineItem1.Term_Months__c = 13;
		lstTestOppLineItems.add(oppLineItem1);

		oppLineItem2.Status__c = 'Won';
		oppLineItem2.Subscription_Start_Date__c = Date.valueOf('2015-09-07');
		oppLineItem2.Subscription_End_Date__c = Date.valueOf('2015-10-31');
		oppLineItem2.Term_Months__c = 13;
		lstTestOppLineItems.add(oppLineItem2);
		
		test.startTest();
    	try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            //Boolean expectedExceptionThrown =  e.getMessage().contains('All subscription end dates must be coterminous') ? true : false;
            //system.assertEquals(expectedExceptionThrown,true);
            system.assertNotEquals(e.getMessage(),NULL);       
		} 
		
		oppLineItem1.Subscription_End_Date__c = Date.valueOf('2015-10-31');
		
		try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            system.assertEquals(e.getMessage(),NULL);       
		}
		        			
		oppLineItem1.Subscription_Start_Date__c = null;
		oppLineItem1.Subscription_End_Date__c = null;
		oppLineItem1.Term_Months__c = null;
		oppLineItem2.Subscription_Start_Date__c = null;
		oppLineItem2.Subscription_End_Date__c = null;
		oppLineItem2.Term_Months__c = null;

		try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            system.assertNotEquals(e.getMessage(),NULL);       
		}
		
		oppLineItem1.Estimated_Completion_Date__c = Date.valueOf('2016-08-31');
		oppLineItem2.Estimated_Completion_Date__c = Date.valueOf('2016-08-07');
		
		try{
        	update lstTestOppLineItems;

        }catch(Exception e){
            system.assertNotEquals(e.getMessage(),NULL);       
		}
    			
		oppLineItem2.Estimated_Completion_Date__c = Date.valueOf('2016-08-31');

		try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            system.assertEquals(e.getMessage(),NULL);       
		}
				
		//non-ACV
		oppLineItem1.Product_Revenue_Type__c = 'PROJ';
		oppLineItem2.Product_Revenue_Type__c = 'PROJ';
		
		oppLineItem1.Subscription_Start_Date__c = null;
		oppLineItem1.Subscription_End_Date__c = null;
		oppLineItem1.Term_Months__c = null;
		oppLineItem2.Subscription_Start_Date__c = null;
		oppLineItem2.Subscription_End_Date__c = null;
		oppLineItem2.Term_Months__c = null;

		try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            system.assertNotEquals(e.getMessage(),NULL);       
		}
				
		oppLineItem1.Subscription_Start_Date__c = Date.valueOf('2015-09-07');
		oppLineItem1.Subscription_End_Date__c = Date.valueOf('2015-09-30');
		oppLineItem1.Term_Months__c = 13;
		oppLineItem2.Subscription_Start_Date__c = Date.valueOf('2015-09-07');
		oppLineItem2.Subscription_End_Date__c = Date.valueOf('2015-09-30');
		oppLineItem2.Term_Months__c = 13;
		
		try{
        	update lstTestOppLineItems;
        }catch(Exception e){
            system.assertEquals(e.getMessage(),NULL);       
		}
		test.stopTest();		
	}
		
}