QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Central Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Private Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Manager of Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Bank-Proprietary Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Corporate/Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-State/Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BDTypeName__c</fullName>
        <label>BDTypeName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Exchange_Country__c</fullName>
        <description>Data migration - from Ian file</description>
        <label>Primary Exchange Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Country_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Country List</label>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Ipreo Vertical with which Opportunity is associated (ex GMG, Corporate).  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AccountBatchJobTest.cls
@isTest
private class GS_AccountBatchJobTest {

   static testmethod void test() {
        Test.startTest();

        List<Follow_Rule_Setting__c> frsList = new List<Follow_Rule_Setting__c>();
        Follow_Rule_Setting__c frs1 = new Follow_Rule_Setting__c(
            Name = 'Opportunity',
            isOpen__c = true
        );
        frsList.add(frs1);
        Follow_Rule_Setting__c frs2 = new Follow_Rule_Setting__c(
            Name = 'OpportunityTeam',
            isOpen__c = true
        );
        frsList.add(frs2);
        insert frsList;

        Account a = new Account(
            Name = '86Research, LTD (Shanghai Office)',
            Status__c = 'Prospect',
            Vertical__c = 'Buyside',
            Account_Type__c = 'Family Office',
            BDTypeName__c = 'Family Office'

        );
        insert a;

        Country_List__c coutL1 = new Country_List__c(Name = 'China');
        Country_List__c coutL2 = new Country_List__c(Name = 'USA');
        insert coutL1;
        insert coutL2;

        Account a2 = new Account(
            Name = '86Research, LTD (Shanghai Office) 2',
            Status__c = 'Prospect',
            Vertical__c = 'Buyside',
            Account_Type__c = 'Family Office',
            BDTypeName__c = 'Family Office',
            BillingCountry = 'China',
            ShippingCountry = 'China',
            Primary_Exchange_Country__c = 'China'
        );
        insert a2;

        a2.BillingCountry = 'USA';
        a2.ShippingCountry = 'USA';
        a2.Primary_Exchange_Country__c = 'USA';
        update a2;

        User u = new User(
            Username = 'test@ipreo_epam.com',
            FirstName = 'Test',
            LastName = 'Ipreo',
            Email = 'test@ipreo.com',
            ProfileId = UserInfo.getProfileId(),
            Alias = 'TIpreo',
            EmailEncodingKey = 'ISO-8859-1',
            TimeZoneSidKey = 'Asia/Shanghai',
            LocaleSidKey = 'zh_CN',
            LanguageLocaleKey = 'en_US'
        );
        insert u;

        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = a.Id;
        atm.UserId = UserInfo.getUserId();
        insert atm;

        AccountTeamMember atm2 = new AccountTeamMember();
        atm2.AccountId = a.Id;
        atm2.UserId = u.Id;
        insert atm2;

        EntitySubscription es = new EntitySubscription(ParentId = a.Id, SubscriberId = u.Id);
        insert es;

        // Schedule the test job
        String sch1 = '0 0 0 3 9 ? 2022';
        String jobName1 = 'GS_AccountTeamMemberBatchScheduleJobTest' + Math.rint(Math.random() * 1000000);
        String jobId = System.schedule(jobName1, sch1, new GS_AccountTeamMemberBatchScheduleJob());

        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals('0 0 0 3 9 ? 2022',ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00',String.valueOf(ct.NextFireTime));


        // Schedule the test job
        String sch2 = '0 0 0 4 9 ? 2022';
        String jobName2 = 'GS_UnfollowAccountBatchScheduleJobTest' + Math.rint(Math.random() * 1000000);
        String jobId2 = System.schedule(jobName2, sch2, new GS_UnfollowAccountBatchScheduleJob());

        CronTrigger ct2 = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId2];
        System.assertEquals('0 0 0 4 9 ? 2022',ct2.CronExpression);
        System.assertEquals(0, ct2.TimesTriggered);
        System.assertEquals('2022-09-04 00:00:00',String.valueOf(ct2.NextFireTime));

        Test.stopTest();

   }
}