QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_of_Active_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Active Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Use to show on email template</description>
        <label>Opportunity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>use to show on email template, copy from work order while order&apos;s status was changed to closed.</description>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>This field use to track work order status, it will increase when work order&apos;s status was change to closed.</description>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Detail_Link__c</fullName>
        <description>use to show on email template, copy from work order while order&apos;s status was changed to closed.</description>
        <label>Work Order Detail Link</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <description>use to show on email template, copy from work order while order&apos;s status was changed to closed.</description>
        <label>Work Order Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <description>use to show on email template, copy from work order while order&apos;s status was changed to closed.</description>
        <label>Work Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Status__c</fullName>
        <label>Work Order Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders_Sales_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Set Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live (Project Still Open)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <displayFormat>WO-{00000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_WorkOrderUpdateACCStatusTHandler.cls
/**************************************************************************************************
 * Name           : GS_WorkOrderUpdateACCStatusTHandler
 * Object         : Work_Order__c/Account
 * Requirement    : STY-00012
 * Target         : When Work Order status is changed, sum the count of active Work Orders of the account.
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-01
 * Modify History : STY-380
 *                 Notify Account team on Work Order closure
 **************************************************************************************************/
public class GS_WorkOrderUpdateACCStatusTHandler implements GS_Triggers.Handler {
    public void handle() {

        List<Account> listOriginAccount;
        List<Id> listAccountIds;
        List<Account> listTargetAccount;

        listOriginAccount = new List<Account>();
        listAccountIds = new List<Id>();
        listTargetAccount = new List<Account>();

        List<Account> accountSet = new List<Account>();
        Set<Id> woIdsSet = new Set<Id>();
        if(Trigger.isupdate) {
            System.debug(LoggingLevel.INFO, '*** GS_WorkOrderUpdateACCStatusTHandler is executed. Action is update ');
            for (Id tempWOId : Trigger.newMap.keySet()) {
                Work_Order__c wo = (Work_Order__c)Trigger.newMap.get(tempWOId);
                Work_Order__c oldWO = (Work_Order__c)Trigger.oldMap.get(tempWOId);
                if (wo.Active__c != oldWO.Active__c || wo.Account__c != oldWO.Account__c) {
                    listAccountIds.add(((Work_Order__c)Trigger.newMap.get(tempWOId)).Account__c);
                    if(wo.Account__c != oldWO.Account__c)
                        listAccountIds.add(((Work_Order__c)Trigger.oldMap.get(tempWOId)).Account__c);
                }
                if(wo.Status__c != oldWO.Status__c && wo.Status__c.containsIgnoreCase('Closed') && wo.Account__c != null) {
                    woIdsSet.add(wo.Id);
                }
            }
            //Add by terry 2015-12-02, update copy order information to account
            for(Work_Order__c wo : [Select Id, Opportunity__r.Name, Sales_Rep__r.Email From Work_Order__c Where Id In: woIdsSet]) {
                Work_Order__c tmpWO = (Work_Order__c)Trigger.newMap.get(wo.Id);
                String TrackingNumber = String.valueOf(Math.random());
                if(TrackingNumber.length() > 20) {
                    TrackingNumber = TrackingNumber.substring(0, 20);
                }else {
                    TrackingNumber = TrackingNumber.substring(0, TrackingNumber.length());
                }
                Account a = new Account(
                    Id = tmpWO.Account__c, 
                    Tracking_Number__c = TrackingNumber,
                    Work_Order_Detail_Link__c = URL.getSalesforceBaseUrl().toExternalForm() + '/' + wo.Id,
                    Work_Order_Name__c = tmpWO.Name,
                    Work_Order_Number__c = tmpWO.Work_Order_Number__c,
                    Work_Order_Status__c = tmpWO.Status__c,
                    Opportunity_Name__c = wo.Opportunity__r.Name,
                    Sales_Rep_Email__c = wo.Sales_Rep__r.Email
                );
                accountSet.add(a);
            }
        } else if(Trigger.isInsert || Trigger.isUndelete) {
            System.debug(LoggingLevel.INFO, '*** GS_WorkOrderUpdateACCStatusTHandler is executed. Action is isInsert or undelete ');
            for (Id tempWOId : Trigger.newMap.keySet()) {
                listAccountIds.add(((Work_Order__c)Trigger.newMap.get(tempWOId)).Account__c);
            }
        } else if( Trigger.isDelete) {
            System.debug(LoggingLevel.INFO, '*** GS_WorkOrderUpdateACCStatusTHandler is executed. Action is isUndelete or isDelete ');
            for (Id tempWOId : Trigger.oldMap.keySet()) {
                listAccountIds.add(((Work_Order__c)Trigger.oldMap.get(tempWOId)).Account__c);
            }
        }

        if (listAccountIds.size() > 0) {
            //listOriginAccount = GS_AccountDMLHandler.getWorkOrdersWithAccount(listAccountIds);
            //map<Id, String> accountIdProdBundleMap = GS_CommonUtility.getAccountProductBundle(listAccountIds);
            listOriginAccount = GS_AccountDMLHandler.getAssetsWorkOrdersByAccount(listAccountIds);
            map<Id, String> accountIdProdBundleMap = GS_CommonUtility.getAccountProductBundle(listAccountIds, listOriginAccount);
            Integer activeWONumber = 0;
            for (Account tempAccount : listOriginAccount) {
                System.debug(LoggingLevel.INFO, '*** tempAccount: ' + tempAccount);
                System.debug(LoggingLevel.INFO, '*** tempAccount.Work_Orders__r.size(): ' + tempAccount.Work_Orders__r.size());
                for(Work_Order__c tempWO : tempAccount.Work_Orders__r) {
                    if(tempWO.Active__c == true) {
                        activeWONumber ++ ;
                    }
                }
                listTargetAccount.add(new Account(Id = tempAccount.Id, No_of_Active_Work_Orders__c = activeWONumber, No_of_All_Work_Orders__c = tempAccount.Work_Orders__r.size(), Product_Bundle__c = accountIdProdBundleMap.get(tempAccount.Id)));
                activeWONumber = 0;
            }

            Update listTargetAccount;
        }
        if(accountSet.size() > 0) update accountSet;
    }
    
}