QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Set Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live (Project Still Open)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_HeatMapBatchJob.cls
global with sharing class GS_HeatMapBatchJob implements Database.Batchable<sObject> , Database.Stateful
{
    public string strAccountIds;
    public string strUserRoleIds;
    public string strHeatMapData; 
       
    global GS_HeatMapBatchJob(string accountIds, string userRoleIds)
    {
        strAccountIds = accountIds;
        strUserRoleIds = userRoleIds;
        strHeatMapData = '';
        //hmc = new GS_HeatMapController();
        //hmc.prepareHeatMapData(mapAccount);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) 
    {
        string taskInnerquery = '(select Id, Products__c, CreatedDate, OwnerId from Tasks where whatId__c in (\'001\',\'006\') and whoId__c = \'003\' and Owner.UserRoleId in '+strUserRoleIds +' and IsDeleted = false and CREATEDDATE = LAST_N_DAYS:730)';
        string eventInnerQuery = '(select Id, Products__c, CreatedDate, OwnerId from Events where whatId__c in (\'001\',\'006\') and whoId__c = \'003\' and Owner.UserRoleId in '+strUserRoleIds +' and IsDeleted = false and CREATEDDATE = LAST_N_DAYS:730)';
        string accountTeamInnerQuery = '(select Id, User.FirstName, User.LastName from AccountTeamMembers where IsDeleted = false)';
        string assetInnerQuery = '(SELECT Id,Status,Product2.Name FROM Assets where IsDeleted = false)';
        string workOrderInnerQuery = '(SELECT Id, Active__c, Product__r.Name FROM Work_Orders__r where IsDeleted = false)';
        
        string query = 'select Id, Name, Status__c,' + taskInnerquery + 
                                                  ','+ eventInnerQuery + 
                                                  ','+ accountTeamInnerQuery + 
                                                  ','+ assetInnerQuery +
                                                  ','+ workOrderInnerQuery +
                        ' from Account where Id in ' + strAccountIds +' ALL ROWS';
        
        system.debug('query in start method of batch--------->>>>>'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Sobject> scope) 
    {
        GS_HeatMapController hmc = new GS_HeatMapController(); 
        strHeatMapData += hmc.populateHeatMapData(scope);
        system.debug('strHeatMapData in EXEC ===='+strHeatMapData);
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        system.debug('strHeatMapData in FINISH ===='+strHeatMapData);
        GS_HeatMapController hmc = new GS_HeatMapController(); 
        hmc.createAttachment(strHeatMapData);  
    }
}