QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Secretary/Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loans Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Syndication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Bus. Dev.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations/IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Company Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Management*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treasury</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NYSE_Program_Tier__c</fullName>
        <label>NYSE Program Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</description>
        <inlineHelpText>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</inlineHelpText>
        <label>No. of Active Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Active Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TSX_Tier__c</fullName>
        <label>TSX Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>GMG Client Tier</description>
        <label>GMG Client Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Set Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live (Project Still Open)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AccountDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_AccountDMLHandler
 * Object         : Account
 * Requirement    : 
 * Target         : DML on Account
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-05-19
 * Modify History :
 **************************************************************************************************/
public class GS_AccountDMLHandler {

    // Get assets of account
    public static List<Account> getAssetsWithAccount(List<Id> accountIds) {

        List<Account> listAccount = [SELECT Id
                                           ,(SELECT Id
                                                   ,Status
                                            FROM Assets)
                                     FROM Account WHERE Id =: accountIds];

        return listAccount;
    }

    // Get Work Orders of account
    public static List<Account> getWorkOrdersWithAccount(List<Id> accountIds) {

        List<Account> listAccount = [SELECT Id
                                           ,(SELECT Id
                                                   ,Active__c
                                             FROM Work_Orders__r)
                                     FROM Account WHERE Id =: accountIds];

        return listAccount;
    }

    // Get Account by ids
    public static List<Account> getAccountsByIds(Set<Id> accountIds) {
        return [SELECT Id
                      ,IsDeleted
                      ,MasterRecordId
                      ,Name
                      ,Type
                      ,Vertical__c
                      ,Status__c
                      ,No_of_Active_Assets__c
                      ,No_of_Active_Work_Orders__c
                      ,No_of_All_Assets__c
                      ,No_of_All_Work_Orders__c
                      ,NYSE_Program_Tier__c
                      ,Tier__c
                      ,LOB__c
                      ,TSX_Tier__c
                      FROM Account
                      WHERE Id in: accountIds];
    }

    // Get Accounts with entitlement
    public static List<Account> getAccountWithEntitlement(Set<Id> accountIds) {
      return [SELECT Id
                      ,IsDeleted
                      ,MasterRecordId
                      ,Name
                      ,Type
                      ,Vertical__c
                      ,Status__c
                      ,No_of_Active_Assets__c
                      ,No_of_Active_Work_Orders__c
                      ,No_of_All_Assets__c
                      ,No_of_All_Work_Orders__c
                      ,NYSE_Program_Tier__c
                      ,Tier__c
                      ,(SELECT Id
                              ,IsPerIncident
                              ,EndDate
                              ,CasesPerEntitlement
                              ,AssetId
                              ,AccountId
                              ,ServiceContractId
                              ,Name
                              ,Type
                              ,BusinessHoursId
                              ,StartDate
                              ,Status
                              ,SlaProcessId
                              ,ContractLineItemId
                        FROM Entitlements
                        LIMIT 1)
                      FROM Account
                      WHERE Id in: accountIds];
    }

    // Get Account team members by Account Id
    public static List<AccountTeamMember> getAccTeamMemsByAccIds(List<Id> accountIds) {
        return [SELECT Id
                      ,AccountId
                      ,UserId
                      ,User.Email
                      ,User.Name
                      ,TeamMemberRole
                      ,AccountAccessLevel
                      FROM AccountTeamMember
                      WHERE AccountId =: accountIds];
    }

    
    // Get assets,Work Order of account
    public static List<Account> getAssetsWorkOrdersByAccount(List<Id> accountIds) {

        List<Account> listAccount = [SELECT Id
        									,No_of_Active_Assets__c
        									,No_of_All_Assets__c
        									,No_of_Active_Work_Orders__c
        									,No_of_All_Work_Orders__c
                                           ,(SELECT Id
                                                   ,Status,Product2.Name,Product2.ProductCode
                                                   ,AccountProductRegionKey__c,Product2.Id
                                                   ,AccountId,Product_Region__c
                                            FROM Assets)
                                            ,(SELECT Id
                                                   ,Active__c,Product__r.Name,Product__r.ProductCode 
                                             FROM Work_Orders__r)
                                     FROM Account WHERE Id =: accountIds];

        return listAccount;
    }
    
}