QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Churn_Reason__c</fullName>
        <label>Churn Reason</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk – Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk – Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk – Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk – Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Touch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Win</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Churn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Churn</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/Desktop_Status__c.object
<CustomObject>
    <description>Account At-Risk Status</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Desktop_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Desktop_Status__c</fullName>
        <label>Desktop Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>At-Risk Status</label>
    <nameField>
        <displayFormat>Status-{0000}</displayFormat>
        <label>Desktop Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>At-Risk Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestAtRiskStatusUpdateAccountTHandler.cls
/**
 * Test class, contains unit tests for validating the GS_AtRiskStatusUpdateAccountTHandler.
 */
@isTest
private class GS_TestAtRiskStatusUpdateAccountTHandler {

    static testMethod void AtRiskTest() {
		
		Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
		
		Test.startTest();
		
		Desktop_Status__c objAtRisk = new Desktop_Status__c();
		objAtRisk.Account__c = testAccount.Id;
		objAtRisk.At_Risk_Reason__c = 'At Risk – Budget';
		objAtRisk.Desktop_Status__c = true;
		
		insert objAtRisk;
		
		objAtRisk = [select Account__c,At_Risk_Reason__c,Desktop_Status__c from Desktop_Status__c where Id =: objAtRisk.Id];
		testAccount = [select Churn__c,Churn_Reason__c from Account where Id =: testAccount.Id];
		
		//system.assertEquals(testAccount.Churn__c, objAtRisk.Desktop_Status__c);
		//system.assertEquals(testAccount.Churn_Reason__c, objAtRisk.At_Risk_Reason__c);
		
		objAtRisk = new Desktop_Status__c();
		objAtRisk.Account__c = testAccount.Id;
		objAtRisk.At_Risk_Reason__c = 'At Risk – Usage';
		objAtRisk.Desktop_Status__c = true;
		
		insert objAtRisk;
		
		objAtRisk = [select Account__c,At_Risk_Reason__c,Desktop_Status__c from Desktop_Status__c where Id =: objAtRisk.Id];
		testAccount = [select Churn__c,Churn_Reason__c from Account where Id =: testAccount.Id];
		
		//system.assertEquals(testAccount.Churn__c, objAtRisk.Desktop_Status__c);
		//system.assertEquals(testAccount.Churn_Reason__c, objAtRisk.At_Risk_Reason__c);
		
		objAtRisk.Desktop_Status__c = true;
		objAtRisk.At_Risk_Reason__c = 'At Risk – Data';
		update objAtRisk;
		
		objAtRisk = [select Account__c,At_Risk_Reason__c,Desktop_Status__c from Desktop_Status__c where Id =: objAtRisk.Id];
		testAccount = [select Churn__c,Churn_Reason__c from Account where Id =: testAccount.Id];
		
		//system.assertEquals(testAccount.Churn__c, objAtRisk.Desktop_Status__c);
		//system.assertEquals(testAccount.Churn_Reason__c, objAtRisk.At_Risk_Reason__c);
				
		Test.stopTest();  
		
    }
}