QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First contract that created asset.</description>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First opportunity that created asset.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset_License__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account associated with asset.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated contract.</description>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Seats__c</fullName>
        <label>No. of Seats</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity that lead to license.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Contract__c.object
<CustomObject>
    <description>Used instead of the standard Contract object to allow queues.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Signed_Date__c</fullName>
        <description>Must be manually populated</description>
        <label>Customer Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evergreen__c</fullName>
        <label>Evergreen</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Executed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to custom contract object</description>
        <inlineHelpText>Link to the Contract with which Opportunity is associated.  Populated when user clicks Add Contract on Opportunity or when user selects an existing Contract with which to associate Opportunity.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>Est. Completion Date based on Est. Completion Date of Opp Products. This field gets updated using Apex Class</description>
        <label>Opportunity Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evergreen__c</fullName>
        <formula>IF( ISPICKVAL(Contract__r.Evergreen__c, &apos;Yes&apos;), True, False)</formula>
        <label>Evergreen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Ops_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sales Ops team member responsible for verification of the Closed Opportunity.  Only editable by Sales Ops.  Required at Opportunity Stage &quot;Closed Won Verified&quot;.</inlineHelpText>
        <label>Sales Ops Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Sales_Ops_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewals</businessProcess>
        <description>Use this if there are one or more ACV renewal products on your opportunity.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Region__c</fullName>
        <label>Data Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <label>Dataset</label>
        <picklist>
            <picklistValues>
                <fullName>Contacts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>To track Delivery Date on Opportunity Products  when project revenue will be realized.</description>
        <inlineHelpText>Date on which project or report is expected to be delivered.  Applies to Project products, only; n/a for subscription products.  Required at Won or at Renewed if Subscription Dates and Term are not entered.</inlineHelpText>
        <label>Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Users__c</fullName>
        <inlineHelpText>Number of users licensed for software products</inlineHelpText>
        <label>No. of Users</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Increase__c</fullName>
        <inlineHelpText>Increase % expected when Opportunity Product is renewed.  When Opportunity is Closed Won Verified, causing a Renewal Opportunity to be created, the ACpV on the Opportunity Product on the Renewal is set to current ACpV + (current ACpV*Renewal Increase %).</inlineHelpText>
        <label>Renewal Increase (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Site_License__c</fullName>
        <label>Site License</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The values of Won/Lost pertain to New Business opportunities and the values of Cancelled/Renewed pertain to Renewal opportunities.</description>
        <inlineHelpText>Required when Opportunity Stage is Closed%.  When Status has not been populated, most fields on page are not validated by system.  Once Status is populated (with either Won/Lost for New Business or Renewed/Cancelled for Renewals), the validations occur.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Product_Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Subscription End Date must be same (coterminous) for all Opportunity Products on the Opportunity.  Req at Won, Renewed if Subscription Start Date and Term populated.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Required at Status &apos;Won&apos; or &apos;Renewed&apos; if Subscription End Date and Term are populated.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <description>Opportunity Term in Months</description>
        <inlineHelpText>Term of subscription, INCLUSIVE of any free period.  Leave blank for non-subscription products.  If entered, Subscription Start Date and Subscription End Date must also be entered.</inlineHelpText>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Data_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Region (AMER, EUR, APAC)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dataset (Contacts or Ownership)</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_TestOpportunityClosedWon.cls
/**************************************************************************************************
 * Name           : GS_TestOpportunityClosedWon
 * Object         : Opportunity/Opportunity Product/Asset/Asset License
 * Requirement    : STY-00170, STY-00172, STY-00178
 * Target         : Test GS_OpportunityClosedWonTHandler
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-09-09
 **************************************************************************************************/

@isTest
private class GS_TestOpportunityClosedWon {
    /***********************************************************************************************************************************
     *Requirement :STY-00170
     *Details     :IF IsChanged(Opportunity.Stage) AND Opportunity.Stage == "Closed Won Verified",FOR EACH opportunity product,
     *             IF Status = Renewed OR Won AND Revenue Type IN (ACV, ACV/TRANS), THEN
     *             IF there does not already exist an asset for the Product AND Opportunity.Account, THEN create an asset record ,Create a license record
     *Requirement :STY-00172
     *Details     :IF IsChanged(Stage) AND Stage == Closed Won Verified, THEN
     *             Clone opportunity except for all calculated fields, and transform certain fields
     *             Clone each opportunity product WHERE Status == Renew OR Won
     *             Clone opportunity team members
     *             Clone opportunity contact roles
     *Requirement :STY-00178
     *Details     :IF IsChanged(Stage) AND Stage == Closed Won Verified, THEN
     *             FOR EACH Opportunity Product
     *             IF Status == Renew OR Won, THEN create Work Order record
     ***********************************************************************************************************************************/

    static testMethod void closeWon1() {

        User testUser = GS_TestDataCreator.createUser('Operations User', 'OperationsUser@test.com', 'APAC');

        List<Follow_Rule_Setting__c> lstFollowRule = new List<Follow_Rule_Setting__c>();
        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        lstFollowRule.add(testSetting1);
        lstFollowRule.add(testSetting2);
        insert lstFollowRule;

        List<String> accNames = new List<String>();
        accNames.add('TestAccount');
        accNames.add('TestAccount1');
        List<Account> testAccounts = GS_TestDataCreator.createAccounts(accNames);

        Account testAccount = testAccounts[0];
        Account testAccount1 = testAccounts[1];

        Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        Partner testPartner1 = GS_TestDataCreator.createPartner(testAccount1, 'Reseller, Distributor', testOpp);
        Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);
        Contract__c testContract = GS_TestDataCreator.createContract('test Contract', testAccount, 'Pending' , 'Shanghai', testContact, 'China' , 'Monthly' , 'Subscription Start Date', 'ZhongShan North Road', '30 Days');
        Attachment testAttachment = GS_TestDataCreator.createAttachment(testContract, 'test Attachment', false , 'Test Contents');
        OpportunityContactRole testConRole = GS_TestDataCreator.createOppConRole(testContact, testOpp, 'Business User');

        // createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
        Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true, 'implementation', 'ACV');

        // createPriceBookEntry(Product2 product, Decimal unitPrice)
        PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);

        // createOppLineItem(Account acc, String name, String recordTypeName, String stageName, String revenueType, String renewalIncrement, String NYSEProgramTier, String verticalType )
        OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp, 'New Business', 100, 200, 50, 'Yes', 'Analec', 'Won', 10000, null, 'ACV', 'NA');

        List<OpportunityLineItem> lstTestOppLineItems = new List<OpportunityLineItem>();

        testContract.Status__c = 'Customer Executed';
        testContract.Evergreen__c = 'No';
        testContract.Customer_Signed_Date__c = Date.valueOf('2015-10-20');
        update testContract;

        oppLineItem1.No_of_Users__c = 100;
        oppLineItem1.Data_Region__c = 'APAC';
        oppLineItem1.Dataset__c = 'Contacts';
        oppLineItem1.Site_License__c = 'APAC';
        oppLineItem1.Subscription_Start_Date__c = Date.valueOf('2015-09-15');
        oppLineItem1.Subscription_End_Date__c = Date.valueOf('2015-09-30');
        oppLineItem1.Term_Months__c = 13;
        oppLineItem1.Estimated_Completion_Date__c = Date.valueOf('2015-08-30');
        oppLineItem1.Renewal_Increase__c = 20;
        lstTestOppLineItems.add(oppLineItem1);

        update lstTestOppLineItems;

        //Opportunity oppResult1 = [select Id,StageName from Opportunity where Id =: testOpp.Id];

        testOpp.StageName = 'Closed Won Verified';
        //oppResult1.Contracted_Value__c = 10;
        testOpp.Sales_Ops_Owner__c = testUser.Id;
        testOpp.Contract__c = testContract.Id;

        GS_GlobalVariables.EXECUTED = false;

        System.debug(LoggingLevel.DEBUG, '*** query number 1: ' + Limits.getQueries());

        Test.startTest();

        System.debug(LoggingLevel.DEBUG, '*** query number 2: ' + Limits.getQueries());

        update testOpp;

        System.debug(LoggingLevel.DEBUG, '*** query number 3: ' + Limits.getQueries());

        Test.stopTest();
        /*
        //data comparison : newly asset and license
        List<Asset> lstAssResult = new List<Asset>();
        List<Asset_License__c> lstLicResult = new List<Asset_License__c>();
        lstAssResult = [select Id, Name, Status, Contract__r.Name, AccountId, Product2Id, Opportunity__c, Contract__c from Asset where Opportunity__r.Id = : testOpp.Id];
        lstLicResult = [select Id, Opportunity__c, Account__c, Contract__c, No_of_Seats__c, Start_Date__c, End_Date__c from Asset_License__c where Opportunity__c = : testOpp.Id];

        if (lstAssResult.size() > 0) {
            System.assertEquals(testAccount.Name + ' ' + testProduct1.Name + ' ' + oppLineItem1.Product_Region__c, lstAssResult[0].Name);
            System.assertEquals(testOpp.AccountId, lstAssResult[0].AccountId);
            System.assertEquals(testProduct1.Id, lstAssResult[0].Product2Id);
            //System.assertEquals(testOpp.Id, lstAssResult[0].Opportunity__c);
            System.assertEquals(testContract.Id, lstAssResult[0].Contract__c);
            System.assertEquals('Inactive', lstAssResult[0].Status);
        }
        if (lstLicResult.size() > 0) {
            System.assertEquals(testOpp.Id, lstLicResult[0].Opportunity__c);
            System.assertEquals(testOpp.AccountId, lstLicResult[0].Account__c);
            System.assertEquals(testContract.Id, lstLicResult[0].Contract__c);
            System.assertEquals(oppLineItem1.No_of_Users__c, lstLicResult[0].No_of_Seats__c);
            System.assertEquals(oppLineItem1.Subscription_Start_Date__c, lstLicResult[0].Start_Date__c);
            System.assertEquals(oppLineItem1.Subscription_End_Date__c, lstLicResult[0].End_Date__c);
        }


        //for newly opportunity, opportunity products
        List<Opportunity> lstOppResult = new List<Opportunity>();
        lstOppResult = [select Id, Name, (SELECT Id, Name, RecordTypeId, Renewal_Status__c, Revenue_Delta_Type__c, CloseDate from Opportunities__r) from Opportunity];
        if (lstOppResult.size() > 0 && lstOppResult[0].Opportunities__r.size() > 0) {
            Opportunity newOppResult = lstOppResult[0].Opportunities__r[0];
            String name = testAccount.Name + ' - Renewal - ' + oppLineItem1.Subscription_End_Date__c.addDays(1).year();
            if (name.length() > 120) {
                name = name.left(120);
            }
            System.assertEquals(name, newOppResult.Name);
            System.assertEquals(GS_TestDataCreator.getRecordType('Renewal', 'Opportunity').Id, newOppResult.RecordTypeId);
            System.assertEquals(oppLineItem1.Subscription_End_Date__c.addDays(1), newOppResult.CloseDate);
            System.assertEquals('Renewal Pending', newOppResult.Renewal_Status__c);
            System.assertEquals('Uptick', newOppResult.Revenue_Delta_Type__c);

            List<OpportunityLineItem> lstOppLItemResult = [select Id, Name, Product_Transaction_Type__c, Status__c, Lost_Cancelled_Reason__c, Estimated_Completion_Date__c, Subscription_Start_Date__c, Subscription_End_Date__c, Prior_Year_ACpV__c from OpportunityLineItem where OpportunityId = :newOppResult.Id ];
            if (lstOppLItemResult.size() > 0) {
                System.assertEquals('Renewal', lstOppLItemResult[0].Product_Transaction_Type__c);
                System.assertEquals(null, lstOppLItemResult[0].Status__c);
                System.assertEquals(null, lstOppLItemResult[0].Lost_Cancelled_Reason__c);
                System.assertEquals(oppLineItem1.Estimated_Completion_Date__c.addYears(1), lstOppLItemResult[0].Estimated_Completion_Date__c);
                System.assertEquals(oppLineItem1.Subscription_End_Date__c.addDays(1), lstOppLItemResult[0].Subscription_Start_Date__c);
                System.assertEquals(oppLineItem1.Subscription_End_Date__c.addYears(1), lstOppLItemResult[0].Subscription_End_Date__c);
                System.assertEquals(oppLineItem1.ACpV__c, lstOppLItemResult[0].Prior_Year_ACpV__c);
            }
        }
        */
    }

    static testMethod void AttachmentCalNumber() {

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);
        Contract__c testContract = GS_TestDataCreator.createContract('test Contract', testAccount, 'Pending', 'Shanghai', testContact, 'China' , 'Monthly' , 'Subscription Start Date', 'ZhongShan North Road', '30 Days');
        Attachment testAttachment = GS_TestDataCreator.createAttachment(testContract, 'test Attachment', false , 'Test Contents');

        delete testAttachment;

    }
}