QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Central Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Private Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Manager of Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Bank-Proprietary Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Corporate/Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-State/Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BDTypeName__c</fullName>
        <label>BDTypeName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</description>
        <inlineHelpText>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</inlineHelpText>
        <label>No. of Active Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Sponsored_Assets__c</fullName>
        <label>No. of Active Sponsored Assets</label>
        <summaryFilterItems>
            <field>Sponsored_Asset__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Sponsored_Asset__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Active Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Sponsored_Assets__c</fullName>
        <label>No. of Sponsored Assets</label>
        <summaryForeignKey>Sponsored_Asset__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AccountUpdateStatusTHandler.cls
/**************************************************************************************************
 * Name           : GS_AccountUpdateStatusTHandler
 * Object         : Account
 * Requirement    : STY-0012
 * Target         : Update Account Status
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-06
 * Modify History : automatically update account type, vertical upon BDTypeName__c 12/10/15
 **************************************************************************************************/
public class GS_AccountUpdateStatusTHandler implements GS_Triggers.Handler {

	public void handle() {
        
        Set<String> accTypeSet = new Set<String>();
        Map<String, String> dependentMap = new Map<String, String>();
        PicklistFieldController controller = new PicklistFieldController();
        Map<String,Set<String>> valueMap = controller.getDependentOptionsImpl('Account', 'Vertical__C', 'Account_Type__c');
        for(String s : valueMap.keySet()) {
            for(String s1 : valueMap.get(s)) {
                accTypeSet.add(s1);
                dependentMap.put(s1, s);
            }
        }
		if (Trigger.isBefore) {
			if (Trigger.isInsert) {
				for (Account tempAcc : (List<Account>)Trigger.new) {

					if (tempAcc.No_of_Active_Sponsored_Assets__c == 0
					        && tempAcc.No_of_Active_Work_Orders__c == 0
					        && tempAcc.No_of_Active_Assets__c == 0) {
						if (tempAcc.No_of_Sponsored_Assets__c == 0
						     && tempAcc.No_of_All_Work_Orders__c == 0
						     && tempAcc.No_of_All_Assets__c == 0) {
							tempAcc.status__c = GS_GlobalVariables.ACCSTATUSPROSPECT;
						} else {
							tempAcc.status__c = GS_GlobalVariables.ACCSTATUSFORMERCLIENT;
						}
					} else {
						tempAcc.status__c = GS_GlobalVariables.ACCSTATUSCLIENT;
					}
                    if(accTypeSet.contains(tempAcc.BDTypeName__c)) {
                        tempAcc.Account_Type__c = tempAcc.BDTypeName__c;
                        tempAcc.Vertical__c = dependentMap.get(tempAcc.BDTypeName__c);
                    }
				}
			}

			if (Trigger.isUpdate) {

				Map<Id, Account> newAccountMap = (Map<Id, Account>)Trigger.newMap;
				Map<Id, Account> oldAccountMap = (Map<Id, Account>)Trigger.oldMap;

				for (Id tempAccId : Trigger.newMap.keySet()) {
					if (newAccountMap.get(tempAccId).No_of_All_Assets__c != oldAccountMap.get(tempAccId).No_of_All_Assets__c
					     || newAccountMap.get(tempAccId).No_of_All_Work_Orders__c != oldAccountMap.get(tempAccId).No_of_All_Work_Orders__c
					     || newAccountMap.get(tempAccId).No_of_Active_Assets__c != oldAccountMap.get(tempAccId).No_of_Active_Assets__c
					     || newAccountMap.get(tempAccId).No_of_Active_Work_Orders__c != oldAccountMap.get(tempAccId).No_of_Active_Work_Orders__c
					     || newAccountMap.get(tempAccId).No_of_Active_Sponsored_Assets__c != oldAccountMap.get(tempAccId).No_of_Active_Sponsored_Assets__c
					     || newAccountMap.get(tempAccId).No_of_Sponsored_Assets__c != oldAccountMap.get(tempAccId).No_of_Sponsored_Assets__c
                         || (!String.isBlank(newAccountMap.get(tempAccId).BDTypeName__c) && newAccountMap.get(tempAccId).BDTypeName__c != oldAccountMap.get(tempAccId).BDTypeName__c)) {

						System.debug(LoggingLevel.INFO, '*** GS_AccountUpdateStatusTHandler is executed when updated and meet filters. ');
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_All_Assets__c: ' + newAccountMap.get(tempAccId).No_of_All_Assets__c);
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_All_Work_Orders__c: ' + newAccountMap.get(tempAccId).No_of_All_Work_Orders__c);
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_Active_Assets__c: ' + newAccountMap.get(tempAccId).No_of_Active_Assets__c);
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_Active_Work_Orders__c: ' + newAccountMap.get(tempAccId).No_of_Active_Work_Orders__c);
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_Active_Sponsored_Assets__c: ' + newAccountMap.get(tempAccId).No_of_Active_Sponsored_Assets__c);
						System.debug(LoggingLevel.INFO, '*** newAccountMap.get(tempAccId).No_of_Sponsored_Assets__c: ' + newAccountMap.get(tempAccId).No_of_Sponsored_Assets__c);


						if ( newAccountMap.get(tempAccId).No_of_Active_Sponsored_Assets__c == 0
						        && newAccountMap.get(tempAccId).No_of_Active_Work_Orders__c == 0
						        && newAccountMap.get(tempAccId).No_of_Active_Assets__c == 0) {
							if (newAccountMap.get(tempAccId).No_of_Sponsored_Assets__c == 0
							     && newAccountMap.get(tempAccId).No_of_All_Work_Orders__c == 0
							     && newAccountMap.get(tempAccId).No_of_All_Assets__c == 0) {
								newAccountMap.get(tempAccId).status__c = GS_GlobalVariables.ACCSTATUSPROSPECT;
							} else {
								newAccountMap.get(tempAccId).status__c = GS_GlobalVariables.ACCSTATUSFORMERCLIENT;
							}
						} else {
							newAccountMap.get(tempAccId).status__c = GS_GlobalVariables.ACCSTATUSCLIENT;
						}
                        if(accTypeSet.contains(newAccountMap.get(tempAccId).BDTypeName__c)) {
                            newAccountMap.get(tempAccId).Account_Type__c = newAccountMap.get(tempAccId).BDTypeName__c;
                            newAccountMap.get(tempAccId).Vertical__c = dependentMap.get(newAccountMap.get(tempAccId).BDTypeName__c);
                        }
					}
				}
			}
		}
	}
}