QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <inlineHelpText>Either Subscription (ACV and ACV/TRANS) or Project (PROJ).  Required to save the Opportunity.</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ACpV__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Annual Contracted Product Value - the Product level breakout for Annual Contracted Value (ACV).</inlineHelpText>
        <label>ACpV</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Revenue_Type__c</fullName>
        <description>Type of revenue associated with the opportunity product</description>
        <inlineHelpText>ACV:  Annual Contracted Value - subscription product.  PROJ:  Project.  ACV/TRANS:  Usage based product.  ACV/PROJ:  Project sold as part of a subscription.</inlineHelpText>
        <label>Product Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_TestOppLineItemUpdateProduct.cls
/**************************************************************************************************
 * Name           : GS_TestOppLineItemUpdateProduct
 * Object         : OpportunityLineItem
 * Requirement    :
 * Target         : Test GS_OppLineItemUpdateProductTHandler
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-09-15
 * Modify History :
 **************************************************************************************************/

@isTest
private class GS_TestOppLineItemUpdateProduct {
	//IF IsNew() OR IsChanged( Account ), THEN Account = Opportunity Product.Opportunity.Account
	//IF IsNew() OR IsChanged( Product ), THEN Product = Opportunity Product.Product 
	//Salesforce does not allow lookup filters on the standard field
	static testMethod void oppLineItemUpdateProduct() {

    	Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
    	Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
    	testSetting1.Name = 'Opportunity';
    	testSetting2.Name = 'OpportunityTeam';
    	testSetting1.isOpen__c = true;
    	testSetting2.isOpen__c = true;
    	insert testSetting1;	
    	insert testSetting2;
    	
		Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
		Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
		
		// createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
		Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true);
        testProduct1.Revenue_Type__c = 'PROJ';
        update testProduct1;

		// createPriceBookEntry(Product2 product, Decimal unitPrice)
		PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);

		// createOppLineItem(PricebookEntry priceEntry, Opportunity opp, String productTransactionType, Decimal acpv, Decimal tcpv, Decimal passThrough)
        OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp, 'New Business', 100, 200, 50, 'Yes', 'Analec');
		oppLineItem1.Product_Revenue_Type__c = 'PROJ';
        update oppLineItem1;
      
		OpportunityLineItem oppResult = [select Id,Product2Id, Product__c, Opportunity.AccountId, Account__c from OpportunityLineItem where OpportunityId =: testOpp.Id];
		
		//system.assertEquals(oppResult.Product__c, oppResult.Product2Id);
		//system.assertEquals(oppResult.Account__c, oppResult.Opportunity.AccountId);

		oppLineItem1.ACpV__c = 150;
		
		update oppLineItem1;
	}
}