QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Central Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Private Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Manager of Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Bank-Proprietary Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Corporate/Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-State/Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BDTypeName__c</fullName>
        <label>BDTypeName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First opportunity that created asset.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Status__c</fullName>
        <inlineHelpText>Set by system:  if Contact has an active User Asset (Contact is associated with an asset with an active subscription) then User Status is &apos;Active&apos;.  Otherwise, &apos;Inactive&apos;.</inlineHelpText>
        <label>User Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_Product_Code__c</fullName>
        <label>Finance Product Code</label>
        <picklist>
            <picklistValues>
                <fullName>BDA - DV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDCG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDE - DF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDFI - DF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDIRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSIQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSP - FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDCRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDPV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDSI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDSY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subgroup__c</fullName>
        <label>Subgroup</label>
        <picklist>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESG - SRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EVENTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VDR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <formula>Text(Asset__r.Product_Region__c )</formula>
        <label>Product Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AddToCampaignControllerTest.cls
@isTest
private class GS_AddToCampaignControllerTest {
    
    static testMethod void testAddToCampaign() {

        Test.startTest();
        List<Product2> products = new List<Product2>();
        Product2 coporateProduct = new Product2(
            Name = 'BD Corporate Governance',
            Vertical__c = 'Corporate',
            ProductCode = 'BDCG',
            Subgroup__c = 'BDC',
            Family = 'BDCG',
            Finance_Product_Code__c = 'BDCG'
        );
        Product2 gmgProduct = new Product2(
            Name = 'BD Advance (Derivatives)',
            Vertical__c = 'GMG',
            ProductCode = 'BDA - DV',
            Subgroup__c = 'BD',
            Family = 'BD Advanced',
            Finance_Product_Code__c = 'DIS'
        );
        products.add(coporateProduct);
        products.add(gmgProduct);
        insert products;


        Account a = new Account(
            Name = '86Research, LTD (Shanghai Office)',
            Status__c = 'Prospect',
            Vertical__c = 'Buyside',
            Account_Type__c = 'Family Office',
            BDTypeName__c = 'Family Office'

        );
        insert a;

        List<Contact> contacts = new List<Contact>();
        Contact c = new Contact(
            LastName = 'Test Contact',
            AccountId = a.Id,
            User_Status__c = 'Active'
        );
        Contact c2 = new Contact(
            LastName = 'Test Contact',
            AccountId = a.Id,
            User_Status__c = 'Inactive'
        );
        contacts.add(c);
        contacts.add(c2);
        insert contacts;

        List<Asset> assets = new List<Asset>();
        Asset asset1 = new Asset(
            Name = 'Asset1',
            AccountId = a.Id,
            Status = 'Active',
            Product_Region__c = 'LATAM',
            // Opportunity__c = o.Id,
            Product2Id = coporateProduct.Id
        );
        Asset asset2 = new Asset(
            Name = 'Asset2',
            AccountId = a.Id,
            Status = 'Active',
            Product_Region__c = 'EMEA',
            // Opportunity__c = o.Id,
            Product2Id = gmgProduct.Id
        );
        assets.add(asset1);
        assets.add(asset2);
        insert assets;

        List<User_Asset__c> userAssets = new List<User_Asset__c>();
        User_Asset__c userAsset1 = new User_Asset__c(
            Active__c = 'Active',
            Asset_Account__c = a.Id,
            Asset__c = asset1.Id,
            User__c = c.Id,
            Role__c = 'User',
            System_Outage_Notification_Opt_Out__c = true
        );
        User_Asset__c userAsset2 = new User_Asset__c(
            Active__c = 'Active',
            Asset_Account__c = a.Id,
            Asset__c = asset2.Id,
            User__c = c2.Id,
            Role__c = 'Comp User',
            System_Outage_Notification_Opt_Out__c = true
        );
        userAssets.add(userAsset1);
        userAssets.add(userAsset2);
        insert userAssets;

        Campaign cam = new Campaign(
            Name = 'Test Campaign 7-22',
            Status = 'In Progress',
            IsActive = true,
            Type = 'Email'
        );
        insert cam;

        Test.stopTest();
        List<User_Asset__c> ConfirmResults = new List<User_Asset__c>();
        ConfirmResults.add(userAsset1);
        ConfirmResults.add(userAsset2);
        PageReference pf = new PageReference('/apex/AddToCampaign');
        Test.setCurrentPage(pf);
        ApexPages.currentPage().getParameters().put('id', cam.Id);
        GS_AddToCampaignController con = new GS_AddToCampaignController();
        con.assetName = 'Asset';
        con.condition = 'e';
        con.contactBillingCountry = 'USA';
        con.billingCondition = 'c';
        con.doSearch();
        con.accountFilter = '2';
        con.vertical = 'GMG';
        con.dynamicProduct();
        con.vertical = 'Corporate';
        con.dynamicProduct();
        con.vertical = 'All';
        con.notificationIndex = '1';
        con.dynamicProduct();
        con.getConditionOptions();
        con.getRoleOptions();
        con.getUserAssets();
        con.getVerticalOptions();
        con.getAccountFilterOptions();
        con.getProductRegionOptions();
        con.getUserStatusOptions();
        con.getNotificationOptions();
        con.selectedProducts = new String[]{'BD Advance (Derivatives)', 'BD Corporate Governance'};
        con.doSearch();
        con.viewResult();
        con.ConfirmResults = ConfirmResults;
        con.addToCampaign();
        con.resetFilter();
        Boolean hasNext = con.hasNext;
        Boolean hasPrevious = con.hasPrevious;
        Integer pageNumber = con.pageNumber;
        con.first();
        con.last();
        con.previous();
        con.next();
        con.cancel();
        
    }

    static testMethod void testDoSearch() {

        Test.startTest();
        List<Product2> products = new List<Product2>();
        Product2 coporateProduct = new Product2(
            Name = 'BD Corporate Governance',
            Vertical__c = 'Corporate',
            ProductCode = 'BDCG',
            Subgroup__c = 'BDC',
            Family = 'BDCG',
            Finance_Product_Code__c = 'BDCG'
        );
        Product2 gmgProduct = new Product2(
            Name = 'BD Advance (Derivatives)',
            Vertical__c = 'GMG',
            ProductCode = 'BDA - DV',
            Subgroup__c = 'BD',
            Family = 'BD Advanced',
            Finance_Product_Code__c = 'DIS'
        );
        products.add(coporateProduct);
        products.add(gmgProduct);
        insert products;


        Account a = new Account(
            Name = '86Research, LTD (Shanghai Office)',
            Status__c = 'Prospect',
            Vertical__c = 'Buyside',
            Account_Type__c = 'Family Office'

        );
        insert a;

        List<Contact> contacts = new List<Contact>();
        Contact c = new Contact(
            LastName = 'Test Contact',
            AccountId = a.Id,
            User_Status__c = 'Active'
        );
        Contact c2 = new Contact(
            LastName = 'Test Contact',
            AccountId = a.Id,
            User_Status__c = 'Inactive'
        );
        contacts.add(c);
        contacts.add(c2);
        insert contacts;

        List<Asset> assets = new List<Asset>();
        Asset asset1 = new Asset(
            Name = 'Asset1',
            AccountId = a.Id,
            Status = 'Active',
            Product_Region__c = 'LATAM',
            // Opportunity__c = o.Id,
            Product2Id = coporateProduct.Id
        );
        Asset asset2 = new Asset(
            Name = 'Asset2',
            AccountId = a.Id,
            Status = 'Active',
            Product_Region__c = 'EMEA',
            // Opportunity__c = o.Id,
            Product2Id = gmgProduct.Id
        );
        assets.add(asset1);
        assets.add(asset2);
        insert assets;

        List<User_Asset__c> userAssets = new List<User_Asset__c>();
        User_Asset__c userAsset1 = new User_Asset__c(
            Active__c = 'Active',
            Asset_Account__c = a.Id,
            Asset__c = asset1.Id,
            User__c = c.Id,
            Role__c = 'User',
            System_Outage_Notification_Opt_Out__c = true
        );
        User_Asset__c userAsset2 = new User_Asset__c(
            Active__c = 'Active',
            Asset_Account__c = a.Id,
            Asset__c = asset2.Id,
            User__c = c2.Id,
            Role__c = 'Comp User',
            System_Outage_Notification_Opt_Out__c = true
        );
        userAssets.add(userAsset1);
        userAssets.add(userAsset2);
        insert userAssets;

        Campaign cam = new Campaign(
            Name = 'Test Campaign 7-22',
            Status = 'In Progress',
            IsActive = true,
            Type = 'Email'
        );
        insert cam;

        Test.stopTest();
        PageReference pf = new PageReference('/apex/AddToCampaign');
        Test.setCurrentPage(pf);
        ApexPages.currentPage().getParameters().put('id', cam.Id);
        GS_AddToCampaignController con = new GS_AddToCampaignController();
        con.assetName = 'Asset';
        con.role = new String[]{'A'};
        con.condition = 'e';
        con.contactBillingCountry = 'USA';
        con.billingCondition = 'c';
        con.vertical = '1';
        con.selectedProducts = new String[]{'A'};
        con.doSearch();
        con.role = null;
        con.selectedProducts = null;
        con.accountFilter = '3';
        con.userStatus = '-';
        con.vertical = '-';
        con.verify();
    }
}