QA_Ipreo/src/objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>MonthlyAccountUpdate</label>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_OppLineItemUpdateProductTHandler.cls
/**************************************************************************************************
 * Name           : GS_OppLineItemCalNetNewBizHander
 * Object         : OpportunityLineItem
 * Requirement    :
 * Target         : Update custom field Product__c, and make it concerted with the standard product.
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-26
 * Modify History :
 **************************************************************************************************/
public class GS_OppLineItemUpdateProductTHandler implements GS_Triggers.Handler {
    public void handle() {
    	if(Trigger.isInsert) {

			Set<Id> setOppIds = new Set<Id>();
			List<Opportunity> lstOpps = new List<Opportunity>();
			Map<Id, Opportunity> mapOpps = new Map<Id, Opportunity>();

    		for(OpportunityLineItem tempOppLineItem : (List<OpportunityLineItem>)Trigger.new) {
    			if(!setOppIds.contains(tempOppLineItem.OpportunityId)){
    				setOppIds.add(tempOppLineItem.OpportunityId);
    			}
    		}

			System.debug(LoggingLevel.INFO, '***GS_OppLineItemUpdateProductTHandler setOppIds: ' + setOppIds);

			lstOpps = GS_OpportunityDMLHandler.getOpportunitiesById(setOppIds);

			if(lstOpps.size() > 0) {
				mapOpps = new Map<Id, Opportunity>(lstOpps);
				for(OpportunityLineItem tempOppLineItem : (List<OpportunityLineItem>)Trigger.new) {
					tempOppLineItem.Account__c = mapOpps.get(tempOppLineItem.OpportunityId).AccountId;
	    			tempOppLineItem.Product__c = tempOppLineItem.Product2Id;
	    		}
			}

    	}

    	if(Trigger.isUpdate) {
    		for(Id tempOppLineItemId : ((Map<Id, OpportunityLineItem>)Trigger.newMap).keySet()) {
    			if(((Map<Id, OpportunityLineItem>)Trigger.newMap).get(tempOppLineItemId).Product2Id != ((Map<Id, OpportunityLineItem>)Trigger.oldMap).get(tempOppLineItemId).Product2Id) {
    				((Map<Id, OpportunityLineItem>)Trigger.newMap).get(tempOppLineItemId).Product__c = ((Map<Id, OpportunityLineItem>)Trigger.newMap).get(tempOppLineItemId).Product2Id;
    			}
    		}
    	}
    }
}