QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Central Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank-Private Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment/Foundation-School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Fund-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Manager of Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Advisor-Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Bank-Proprietary Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Corporate/Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-State/Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Fund-Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BDTypeName__c</fullName>
        <label>BDTypeName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <inlineHelpText>Either Subscription (ACV and ACV/TRANS) or Project (PROJ).  Required to save the Opportunity.</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Ipreo Vertical with which Opportunity is associated (ex GMG, Corporate).  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_OppTeamMemberTest.cls
@isTest
private class GS_OppTeamMemberTest {
    
    static testMethod void testOppTeamMemeber() {

        Test.startTest();
        Profile p = [Select Id From Profile Where Name = 'Sales User' limit 1];
        // update u;
        User u = new User(
            Username = 'test@ipreo_epam.com',
            FirstName = 'Test',
            LastName = 'Ipreo',
            Email = 'test@ipreo.com',
            ProfileId = p.Id,
            Alias = 'TIpreo',
            EmailEncodingKey = 'ISO-8859-1',
            TimeZoneSidKey = 'Asia/Shanghai',
            LocaleSidKey = 'zh_CN',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        List<Follow_Rule_Setting__c> frsList = new List<Follow_Rule_Setting__c>();
        Follow_Rule_Setting__c frs1 = new Follow_Rule_Setting__c(
            Name = 'Opportunity',
            isOpen__c = true
        );
        frsList.add(frs1);
        Follow_Rule_Setting__c frs2 = new Follow_Rule_Setting__c(
            Name = 'OpportunityTeam',
            isOpen__c = true
        );
        frsList.add(frs2);
        insert frsList;

        Account a = new Account(
            Name = '86Research, LTD (Shanghai Office)',
            Status__c = 'Prospect',
            Vertical__c = 'Buyside',
            Account_Type__c = 'Family Office',
            BDTypeName__c = 'Family Office'

        );
        insert a;

        Opportunity o = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = a.Id,
            StageName = 'Opportunity Identified',
            CloseDate = System.today().addDays(30),
            Revenue_Type__c = 'Subscription'
        );
        insert o;

        OpportunityTeamMember otm = new OpportunityTeamMember(
            OpportunityId = o.Id,
            UserId = u.Id
        );
        insert otm;

        List<EntitySubscription> enSubResult = [select ParentId,SubscriberId from EntitySubscription where SubscriberId = :u.Id];
        if(enSubResult.size() > 0)
        {
            System.assertEquals(a.Id, enSubResult[0].ParentId);
        }

        Test.stopTest();

        delete otm;

        PicklistFieldController.PicklistEntryWrapper pew = new PicklistFieldController.PicklistEntryWrapper();
        pew.active = 'true';
        pew.defaultValue = 'Bank';
        pew.label = 'Bank';
        pew.value = 'Bank';
        pew.validFor = 'gAAA';
    }
}