QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</description>
        <inlineHelpText>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</inlineHelpText>
        <label>No. of Active Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Active Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>AccountProductRegionKey__c</fullName>
        <externalId>true</externalId>
        <label>AccountProductRegionKey</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AccountStatsTHandler.cls
/**************************************************************************************************
 * Name           : GS_AccountStatsTHandler
 * Object         : Account
 * Requirement    : 
 * Target         : To update No_Of_XXX on fields on Account during Account merge.
 * Refer classes  :
 * Author         : Uday Bikkumalla
 * Create Date    : 2016-08-25
 * Modify History : Ambadas Joshi, Added code to fix duplicate asset creation issue during CWV process(SPS-1509). 
 **************************************************************************************************/
public class GS_AccountStatsTHandler implements GS_Triggers.Handler {
	List<ID> accountIds;
	List<Account> listOriginAccount;
	List<Account> listTargetAccount;
	
	public void handle() {
	accountIds = new List<ID>();
	  if(Trigger.isUpdate && Trigger.isAfter){
       		accountIds.addAll(Trigger.newMap.keySet());
	   		updateAssetStats(accountIds);
    	}
	}
	
	/*Update fields on Account during merge process */
	public void updateAssetStats(List<ID> accountIds){
		/*SPS-1509*/
		String strSeprator = '_';
		String strAccId = '';
		String strProId = '';
		String strRegion = '';
		list<Asset> lstUpdateAsset = new list<Asset>();
		
		listTargetAccount = new List<Account>();
		if(accountIds.size()> 0){
			listOriginAccount = GS_AccountDMLHandler.getAssetsWorkOrdersByAccount(accountIds);
			Integer activeAssetNum = 0;
			Integer activeWONumber = 0;
			/*map<Id, String> accountIdProdBundleMap = GS_CommonUtility.getAccountProductBundle(accountIds);*/
			map<Id, String> accountIdProdBundleMap = GS_CommonUtility.getAccountProductBundle(accountIds,listOriginAccount);
			for (Account tempAccount : listOriginAccount) {
				for (Asset tempAsset : tempAccount.Assets) {
					if (tempAsset.Status == 'Active') {
						activeAssetNum ++ ;
					}
					
					/*SPS-1509*/
					strAccId = tempAsset.AccountId != NULL ? String.valueOf(tempAsset.AccountId) : '';
					strProId = tempAsset.Product2Id != NULL ? String.valueOf(tempAsset.Product2Id) : '';
					strRegion = tempAsset.Product_Region__c != NULL ? String.valueOf(tempAsset.Product_Region__c) : '';
					string tempAssetKey = strAccId + strSeprator + strProId + strSeprator + strRegion;
					
					if(tempAssetKey != tempAsset.AccountProductRegionKey__c){
						tempAsset.AccountProductRegionKey__c = tempAssetKey;
						lstUpdateAsset.add(tempAsset);
					}
				}
				for(Work_Order__c tempWO : tempAccount.Work_Orders__r) {
                    if(tempWO.Active__c == true) {
                        activeWONumber ++ ;
                    }
                }	
				if(tempAccount.Assets.size() != ((Account)Trigger.newMap.get(tempAccount.id)).No_of_All_Assets__c 
				|| tempAccount.Work_Orders__r.size() != ((Account)Trigger.newMap.get(tempAccount.id)).No_of_All_Work_Orders__c){
            	  		listTargetAccount.add(new Account(Id = tempAccount.Id, No_of_Active_Assets__c = activeAssetNum, No_of_All_Assets__c = tempAccount.Assets.size(), No_of_Active_Work_Orders__c = activeWONumber, No_of_All_Work_Orders__c = tempAccount.Work_Orders__r.size(), Product_Bundle__c = accountIdProdBundleMap.get(tempAccount.Id)));
            	  }
				activeAssetNum = 0;
				activeWONumber = 0;				
			}
		} 
		if(listTargetAccount.size() > 0){
			try{
				update listTargetAccount;
			}
			catch(System.DmlException ex){
				throw ex;
			}
		}
		
		/*SPS-1509*/
		if(lstUpdateAsset.size() > 0){
			try{
				update lstUpdateAsset;
			}
			catch(System.DmlException ex){
				throw ex;
			}
		}
	}
}