QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Secretary/Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loans Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Syndication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Bus. Dev.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations/IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Company Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Management*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treasury</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NYSE_Program_Tier__c</fullName>
        <label>NYSE Program Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSX_Tier__c</fullName>
        <label>TSX Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Announce_Deal__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked when the Deal Announcement (email) should be sent at Closed Won Verified or unchecked for confidential deals.  Defaults to checked for new Opportunity and resets to unchecked AFTER announcement is sent.</inlineHelpText>
        <label>Announce Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Announcement_Sent__c</fullName>
        <description>Flag to indicate if the closed won verified deal announcement is sent.  Used to inhibit a deal announcement from being sent twice if the opportunity is re-set to Closed Won Verified.</description>
        <inlineHelpText>Most recent date on which Deal Announcement was sent.  Set by system on sending of announcement.</inlineHelpText>
        <label>Deal Announcement Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>Est. Completion Date based on Est. Completion Date of Opp Products. This field gets updated using Apex Class</description>
        <label>Opportunity Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <inlineHelpText>Line of Business.  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>LOB</label>
        <picklist>
            <controllingField>Vertical__c</controllingField>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Secretary/Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI Trading*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loans Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Syndication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Bus. Dev.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations/IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Company Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research-Industry/Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Management*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treasury</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NYSE_Program_Tier__c</fullName>
        <inlineHelpText>Indicates that the Opportunity is associated with a NYSE Program (NYSE is subsidizing at least one Opportunity Product on the Opportunity).  Defaults from Account.  If selected, &quot;Non-Subsidized Contracted Value&quot; must also be populated.</inlineHelpText>
        <label>NYSE Program Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSX_Tier__c</fullName>
        <label>TSX Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Verified_Date__c</fullName>
        <description>Stores the date when the Opportunity Stage was changed to &quot;Closed Won Verified&quot; or &quot;Closed Cancelled Verified&quot;</description>
        <inlineHelpText>Stores the date when the Opportunity Stage was changed to &quot;Closed Won Verified&quot; or &quot;Closed Cancelled Verified&quot;</inlineHelpText>
        <label>Verified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Ipreo Vertical with which Opportunity is associated (ex GMG, Corporate).  Defaults from Account when Opportunity is saved.  Can be updated.  Selection of Vertical filters the list of values for LOB.  Required at Closed Won Sales, Closed Won Verified.</inlineHelpText>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_OpportunityAssignValueTHandler.cls
/**************************************************************************************************
 * Name           : GS_OpportunityAssignValueTHandler
 * Object         : Opportunity
 * Requirement    : STY-00011, STY-00007, STY-00230
 * Target         : Assign value when an opportunity is created or updated
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-02
 * Modify History : 2017-02-10 - SPS-1699
 * Changes		  : Added Logic to compute Est.Completion Date, Cancel reason based on Opp.Products
 **************************************************************************************************/
public class GS_OpportunityAssignValueTHandler implements GS_Triggers.Handler{

    public void handle() {

        // Related account information
        Set<Id> setAccIds = new Set<Id>();
        List<Account> lstAcc = new List<Account>();
        Map<Id, Account> mapAcc = new Map<Id, Account>();

        for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
            if(!setAccIds.contains(tempOpp.AccountId)) {
                setAccIds.add(tempOpp.AccountId);
            }
        }

        lstAcc = GS_AccountDMLHandler.getAccountsByIds(setAccIds);

        if(lstAcc.size() > 0) {
            mapAcc = new Map<Id, Account>(lstAcc);
        }
        assginOppVertical(mapAcc);
        assignNYSEProgramTier(mapAcc);
        assginOppLOB(mapAcc);
        assginTSXTier(mapAcc);
        assignOppFieldValues(mapAcc);
        setCWVDetails();
        //assignOppNameWhenClose(mapAcc);
    }

    // On opportunity, If vertical is blank, default the vertical as account's vertical
    private void assginOppVertical(Map<Id, Account> mapAccounts) {
        if(Trigger.isInsert){
            if(Trigger.isBefore) {
                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    if(String.isBlank(tempOpp.Vertical__c)) {
                        tempOpp.Vertical__c = mapAccounts.get(tempOpp.AccountId).Vertical__c;
                    }
                }
            }
        }
    }

    // On opportunity, If LOB is blank, default the LOB as account's LOB
    private void assginOppLOB(Map<Id, Account> mapAccounts) {
        if(Trigger.isInsert){
            if(Trigger.isBefore) {
                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    if(String.isBlank(tempOpp.LOB__c)) {
                        tempOpp.LOB__c = mapAccounts.get(tempOpp.AccountId).LOB__c;
                    }
                }
            }
        }
    }

    // Opportunity
    // IF record created, THEN
    // IF record created AND NYSE Program Tier == null AND Account.NYSE Program Tier ≠ "Tier A", THEN NYSE Program Tier = Account.NYSE Program Tier
    // IF record created AND NYSE Program Tier == null AND Account.NYSE Program Tier == "Tier A" AND Record Type.Name == "New Business", THEN NYSE Program Tier = "Tier A"
    private void assignNYSEProgramTier(Map<Id, Account> mapAccounts) {
        if(Trigger.isInsert){
            if(Trigger.isBefore) {

                RecordType rtNewBusiness = GS_RecordTypeUtility.getRecordType(GS_GlobalVariables.OPPRTNEWBUSINESS, 'Opportunity');

                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    if(    String.isBlank(tempOpp.NYSE_Program_Tier__c)
                        && mapAccounts.get(tempOpp.AccountId).NYSE_Program_Tier__c != GS_GlobalVariables.NYSEPROGRAMTIERA) {
                        tempOpp.NYSE_Program_Tier__c = mapAccounts.get(tempOpp.AccountId).NYSE_Program_Tier__c;
                    } else if(     String.isBlank(tempOpp.NYSE_Program_Tier__c)
                                && mapAccounts.get(tempOpp.AccountId).NYSE_Program_Tier__c == GS_GlobalVariables.NYSEPROGRAMTIERA
                                && tempOpp.RecordTypeId == rtNewBusiness.Id) {
                        tempOpp.NYSE_Program_Tier__c = GS_GlobalVariables.NYSEPROGRAMTIERA;
                    }
                }
            }
        }
    }
	// On opportunity, Default the TSX Tier as account's TSX Tier
    private void assginTSXTier(Map<Id, Account> mapAccounts) {
        if(Trigger.isInsert){
            if(Trigger.isBefore) {
                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    if(String.isBlank(tempOpp.TSX_Tier__c)) {
                        tempOpp.TSX_Tier__c = mapAccounts.get(tempOpp.AccountId).TSX_Tier__c;
                    }
                }
            }
        }
    }    

    // Format opportunity Name when closed.
   /* private void assignOppNameWhenClose(Map<Id, Account> mapAccounts) {
        if(Trigger.isUpdate){
            if(Trigger.isBefore) {

                String strSeparator = ' - ';

                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    if(String.isNotBlank(tempOpp.AccountId) && (tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDLOST || tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDCANCELLEDVERIFIED || tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDCANCELLED)) {
                        tempOpp.Name = mapAccounts.get(tempOpp.AccountId).Name +
                                       (String.isNotBlank(tempOpp.Product_Bundle__c) ? (strSeparator + tempOpp.Product_Bundle__c) : '') +
                                       strSeparator +
                                       tempOpp.StageName +
                                       (tempOpp.CloseDate != NULL ? (strSeparator + String.valueOf(tempOpp.CloseDate.year())) : '');
                        if (tempOpp.Name.length() > 120) {
                            tempOpp.Name = tempOpp.Name.left(120);
                        }
                    }
                }
            }
        }
    }*/
    
    // Compute and Assign ProductBundle for opportunity.
    /*
    Compute and assign Cancel Reason and Est Completion Date
    */
    private void assignOppFieldValues(Map<Id, Account> mapAccounts) {
        if(Trigger.isUpdate){
            if(Trigger.isBefore) {

                Map<ID,Opportunity> mapTargetOpp = new Map<ID,Opportunity>(GS_OpportunityDMLHandler.getOpportunitiesWithLineItemsById(Trigger.newMap.keySet()));
                for(Opportunity tempOpp : (List<Opportunity>)Trigger.new) {
                    Opportunity Opp = mapTargetOpp.get(tempOpp.id);
                    Opportunity oldOpp = (Opportunity)Trigger.oldMap.get(tempOpp.id);
                    if(String.isNotBlank(tempOpp.AccountId) && (tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDLOST || tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDCANCELLEDVERIFIED || tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDCANCELLED)) {
                        tempOpp.Product_Bundle__c = GS_CommonUtility.getProductBundlerForOpp(Opp,false);
                    }
                    String tempBundle = GS_CommonUtility.getProductBundlerForOpp(Opp,true);
                    if(String.isNotBlank(tempOpp.AccountId) && tempOpp.StageName.contains('Won') && tempOpp.Product_Bundle__c != tempBundle){   
                        tempOpp.Product_Bundle__c = GS_CommonUtility.getProductBundlerForOpp(Opp,true); 
                    }
                    if(oldOpp.StageName != GS_GlobalVariables.OPPCLOSEDCANCELLEDVERIFIED && tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDCANCELLEDVERIFIED){   
                        tempOpp.Cancel_Reason__c = GS_CommonUtility.getCancelReasonforOpp(Opp); 
                    }
                    if(oldOpp.StageName != GS_GlobalVariables.OPPCLOSEDWONVERIFIED && tempOpp.StageName == GS_GlobalVariables.OPPCLOSEDWONVERIFIED){   
                        tempOpp.Estimated_Completion_Date__c = GS_CommonUtility.getEstCompletionDate(Opp); 
                    }                    
                    
                }
            }
        }
    }    
    
    private void setCWVDetails(){
    	if(Trigger.isUpdate && Trigger.isBefore){
    		for(ID oppId : Trigger.newMap.keySet()){
    			Opportunity newOpp = (Opportunity)Trigger.newMap.get(oppId);
    			Opportunity oldOpp = (Opportunity)Trigger.oldMap.get(oppId);
    			if(newOpp != null && oldOpp != null){
    				if(newOpp.StageName != oldOpp.StageName && newOpp.StageName == GS_GlobalVariables.OPPCLOSEDWONVERIFIED){
    					newOpp.Verified_Date__c = System.today();
	    				/*
	    				if(newOpp.Announce_Deal__c){
							newOpp.Announce_Deal__c = false;	
	    					newOpp.Deal_Announcement_Sent__c = System.now();    					
	    				}
	    				*/
    				}	
    			}
    		}
    	}
    }
   
   
  
}