QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset_License__c.object
<CustomObject>
    <fields>
        <fullName>Active_Need_to_Be_Updated__c</fullName>
        <formula>OR(
    AND(
         Auto_Populated_Active_Status__c = true
        , NOT(ISPICKVAL(Status__c, &apos;Active&apos;))
       )
   ,AND(
         Auto_Populated_Active_Status__c = false
        , NOT(ISPICKVAL(Status__c, &apos;Inactive&apos;))
       )
)</formula>
        <label>Active Need to Be Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Populated_Active_Status__c</fullName>
        <formula>AND(
      Start_Date__c &lt;= DATEVALUE(NOW())
     ,End_Date__c &gt;= DATEVALUE(NOW())
)</formula>
        <label>Auto Populated Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_LicenseUpdateStatusBatch.cls
global class GS_LicenseUpdateStatusBatch implements Database.Batchable<sObject> {
    public String query;
    String strSaveErrResult = '';
    
    global GS_LicenseUpdateStatusBatch() {
    	this.query = 'SELECT Id,Status__c,Auto_Populated_Active_Status__c FROM Asset_License__c WHERE Active_Need_to_Be_Updated__c = true Limit 9999';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
    	return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Sobject> scope) {

		List<Asset_License__c> listTargetLicense;
		listTargetLicense = new List<Asset_License__c>();

		for(Asset_License__c tempLicense : (List<Asset_License__c>)scope) {
			tempLicense.Status__c = tempLicense.Auto_Populated_Active_Status__c ? 'Active' : 'Inactive';
			listTargetLicense.add(tempLicense);
		}
		List<Database.SaveResult> saveResults = Database.update(listTargetLicense, false);
        for(Database.SaveResult res : saveResults) {
            if(!res.isSuccess()) {
                for(Database.Error err : res.getErrors()) {
                    strSaveErrResult += err.getFields() + ': ' + err.getMessage() + '\n';
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

        if(String.isNotBlank(strSaveErrResult)) {
            GS_EmailUtility.Send(UserInfo.getUserId(), 'Account Status Calucation Exception on License ' + String.valueOf(Datetime.now()), strSaveErrResult);
        }

    }
}