QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</description>
        <inlineHelpText>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</inlineHelpText>
        <label>No. of Active Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <label>No. of Active Assets</label>
        <summaryFilterItems>
            <field>User_Asset__c.Active__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>User_Asset__c.User__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Sponsored_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sponsored Assets</relationshipLabel>
        <relationshipName>Sponsored_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Sponsored Accounts</relationshipLabel>
        <relationshipName>Sponsored_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsored Asset</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Sponsored Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <formula>Text(Asset__r.Product_Region__c )</formula>
        <label>Product Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestAssetHandler.cls
@isTest
private class GS_TestAssetHandler {
    static testMethod void assetHandler() {

        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Account testAccount2 = GS_TestDataCreator.createAccount('TestAccount2');
        Contact testContact = GS_TestDataCreator.createContact('TestContact', testAccount);
        Contact testContact2 = GS_TestDataCreator.createContact('TestContact', testAccount2);
        Product2 testProduct = GS_TestDataCreator.createProduct('TestProduct', true, false);
        Asset testAsset = GS_TestDataCreator.createAsset(testAccount, 'TestAsset', testProduct, 'NA');

        Sponsored_Asset__c testSpoAss = new Sponsored_Asset__c();
        testSpoAss.Account_Name__c = testAccount.Id;
        testSpoAss.Asset_Name__C = testAsset.Id;
        testSpoAss.Active__c = false;
        insert testSpoAss;

        User_Asset__c testUserAss1 = new User_Asset__c();
        testUserAss1.User__c = testContact.Id;
        testUserAss1.Asset__c = testAsset.Id;
        insert testUserAss1;

        User_Asset__c testUserAss2 = new User_Asset__c();
        testUserAss2.User__c = testContact2.Id;
        testUserAss2.Asset__c = testAsset.Id;

        try{
            insert testUserAss2;        
        }catch(Exception e){
           System.debug('The following exception has occurred: ' + e.getMessage());
        } 

        testAsset.Status = 'Active';
        testAsset.Product_Region__c = 'LATAM';
        update testAsset;
		
		Set<ID> setAssetIds = new Set<ID>();
		setAssetIds.add(testAsset.id);
		GS_AssetUpdateUserAssetStatusTHandler.updateUserAssets(setAssetIds); 
		GS_AssetUpdateUserAssetStatusTHandler.sendEmailOnError('Test Failure Message');
        List<Account> lstAccoutResult = [select Id,No_of_Active_Assets__c,No_of_All_Assets__c from Account where Id = :testAccount.Id];
        if(lstAccoutResult.size() > 0)
        {
            System.assertEquals(1, lstAccoutResult[0].No_of_Active_Assets__c);
            System.assertEquals(1, lstAccoutResult[0].No_of_All_Assets__c);
        }
        List<User_Asset__c> lstUAResult = [select Id, Active__c from User_Asset__c where Asset__c = :testAsset.Id];
        if(lstUAResult.size() > 0)
        {
            for(User_Asset__c uAsset : lstUAResult)
            {
                System.assertEquals('Active', uAsset.Active__c);
            }
        }
        List<Sponsored_Asset__c> lstSAResult = [select Id, Active__c from Sponsored_Asset__c where Asset_Name__C = :testAsset.Id];
        if(lstSAResult.size() > 0)
        {
            for(Sponsored_Asset__c sAsset : lstSAResult)
            {
                System.assertEquals(true, sAsset.Active__c);
            }
        }
    }
    
    
}