QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Contract__c.object
<CustomObject>
    <description>Used instead of the standard Contract object to allow queues.</description>
    <fields>
        <fullName>Customer_Signed_Date__c</fullName>
        <description>Must be manually populated</description>
        <label>Customer Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evergreen__c</fullName>
        <label>Evergreen</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Executed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to custom contract object</description>
        <inlineHelpText>Link to the Contract with which Opportunity is associated.  Populated when user clicks Add Contract on Opportunity or when user selects an existing Contract with which to associate Opportunity.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>Est. Completion Date based on Est. Completion Date of Opp Products. This field gets updated using Apex Class</description>
        <label>Opportunity Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evergreen__c</fullName>
        <formula>IF( ISPICKVAL(Contract__r.Evergreen__c, &apos;Yes&apos;), True, False)</formula>
        <label>Evergreen</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewals</businessProcess>
        <description>Use this if there are one or more ACV renewal products on your opportunity.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ACpV__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Annual Contracted Product Value - the Product level breakout for Annual Contracted Value (ACV).</inlineHelpText>
        <label>ACpV</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Data_Region__c</fullName>
        <label>Data Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <label>Dataset</label>
        <picklist>
            <picklistValues>
                <fullName>Contacts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>To track Delivery Date on Opportunity Products  when project revenue will be realized.</description>
        <inlineHelpText>Date on which project or report is expected to be delivered.  Applies to Project products, only; n/a for subscription products.  Required at Won or at Renewed if Subscription Dates and Term are not entered.</inlineHelpText>
        <label>Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Users__c</fullName>
        <inlineHelpText>Number of users licensed for software products</inlineHelpText>
        <label>No. of Users</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Increase__c</fullName>
        <inlineHelpText>Increase % expected when Opportunity Product is renewed.  When Opportunity is Closed Won Verified, causing a Renewal Opportunity to be created, the ACpV on the Opportunity Product on the Renewal is set to current ACpV + (current ACpV*Renewal Increase %).</inlineHelpText>
        <label>Renewal Increase (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Site_License__c</fullName>
        <label>Site License</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The values of Won/Lost pertain to New Business opportunities and the values of Cancelled/Renewed pertain to Renewal opportunities.</description>
        <inlineHelpText>Required when Opportunity Stage is Closed%.  When Status has not been populated, most fields on page are not validated by system.  Once Status is populated (with either Won/Lost for New Business or Renewed/Cancelled for Renewals), the validations occur.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Product_Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Subscription End Date must be same (coterminous) for all Opportunity Products on the Opportunity.  Req at Won, Renewed if Subscription Start Date and Term populated.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Required at Status &apos;Won&apos; or &apos;Renewed&apos; if Subscription End Date and Term are populated.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <description>Opportunity Term in Months</description>
        <inlineHelpText>Term of subscription, INCLUSIVE of any free period.  Leave blank for non-subscription products.  If entered, Subscription Start Date and Subscription End Date must also be entered.</inlineHelpText>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Data_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Region (AMER, EUR, APAC)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dataset (Contacts or Ownership)</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated contract</description>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Region__c</fullName>
        <label>Data Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <label>Dataset</label>
        <picklist>
            <picklistValues>
                <fullName>Contacts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>No_of_Users__c</fullName>
        <description>Number of Users</description>
        <inlineHelpText>Number of Users</inlineHelpText>
        <label>No. of Users</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Site_License__c</fullName>
        <label>Site License</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Set Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live (Project Still Open)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>Cancellation</fullName>
        <active>true</active>
        <label>Cancellation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <label>Implementation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestOppClosedHandler.cls
/**************************************************************************************************
 * Name           : GS_TestOppClosedHandler
 * Object         : Opportunity/Opportunity Product/Work Order
 * Requirement    : 
 * Target         : Test GS_OpportunityClosedTHandler, that handler generate cancelled Wo if the opportunit is closed
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-09-09
 **************************************************************************************************/
@isTest
private class GS_TestOppClosedHandler {

    static testMethod void oppCloseHandler() {

        Test.startTest();
        User testUser = GS_TestDataCreator.createUser('Operations User', 'OperationsUser@test.com', 'APAC');

        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Account testAccount1 = GS_TestDataCreator.createAccount('TestAccount1');
        Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'Renewal', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        Partner testPartner =GS_TestDataCreator.createPartner(testAccount1,'Reseller, Distributor',testOpp);
        Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);
        Contract__c testContract = GS_TestDataCreator.createContract('test Contract', testAccount, 'Pending' , 'Shanghai', testContact, 'China' , 'Monthly' ,'Subscription Start Date', 'ZhongShan North Road', '30 Days');  
        Attachment testAttachment = GS_TestDataCreator.createAttachment(testContract, 'test Attachment', false , 'Test Contents');
        OpportunityContactRole testConRole = GS_TestDataCreator.createOppConRole(testContact, testOpp, 'Business User');
        
        Product2 testProduct = GS_TestDataCreator.createProduct('TestProduct1', true, true, 'implementation', 'ACV');
        PricebookEntry testPBEntry = GS_TestDataCreator.createPriceBookEntry(testProduct, 100);
       //Uday 24062016: Changed the Pass Through parameter as zero, as there is a new validation to have zero or null for cancelled opportunity products
        OpportunityLineItem oppLineItem = GS_TestDataCreator.createOppLineItem(testPBEntry, testOpp, 'Renewal', 100, 200, 0, 'Yes', 'Analec','Renewed',10000, null, 'ACV', 'NA');
        
        testContract.Status__c = 'Customer Executed';
        testContract.Evergreen__c = 'No';
        testContract.Customer_Signed_Date__c = Date.valueOf('2015-10-20');
        update testContract;
        Test.stopTest();

        oppLineItem.No_of_Users__c = 100;
        oppLineItem.Data_Region__c = 'APAC';
        oppLineItem.Dataset__c = 'Contacts';
        oppLineItem.Site_License__c = 'APAC';
        oppLineItem.Subscription_Start_Date__c = Date.valueOf('2015-09-15');
        oppLineItem.Subscription_End_Date__c = Date.valueOf('2015-09-30');
        oppLineItem.Term_Months__c = 0;
        oppLineItem.Estimated_Completion_Date__c = Date.valueOf('2015-08-30');
        oppLineItem.Renewal_Increase__c = 20;
        oppLineItem.ACpV__c = 0;
        oppLineItem.UnitPrice = 0;
        //oppLineItem.Work_Order__r = testWO1;
        oppLineItem.Status__c = 'Cancelled';
        oppLineItem.Lost_Cancelled_Reason__c = 'Test Reason';
        oppLineItem.Cancel_Comment__c = 'Test Reason';
        update oppLineItem;

        testOpp.Non_Subsidized_Contracted_Value__c = 100000;
        testOpp.LOB__c = 'Equity - Research, Sales & Trading';
        testOpp.StageName = GS_GlobalVariables.OPPCLOSEDWONVERIFIED;
        testOpp.Sales_Ops_Owner__c = testUser.Id;
        testOpp.Contract__c = testContract.Id;

        GS_GlobalVariables.EXECUTED = false;
        update testOpp;

        System.debug(LoggingLevel.INFO, '*** testOpp: ' + testOpp);

        List<Work_Order__c> generatedWO = [SELECT Id, RecordType.Name, Product__c, Opportunity__c from Work_Order__c];
        System.debug(LoggingLevel.INFO, '*** generatedWO: ' + generatedWO);
        RecordType cancelRT = [SELECT Id FROM RecordType Where Name = 'Cancellation' AND SobjectType = 'Work_Order__c'];
        System.assertEquals(1, generatedWO.size());
        System.assertEquals(cancelRT.Id, generatedWO[0].RecordType.Id);

    }

	static testMethod void testOppCloseHandler_methodOne() {

        Test.startTest();
        User testUser = GS_TestDataCreator.createUser('Operations User', 'OperationsUser@test.com', 'APAC');

        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Account testAccount1 = GS_TestDataCreator.createAccount('TestAccount1');
    	Opportunity testOpp;
    	OpportunityLineItem oppLineItem;
    	System.runAs(testUser){
         testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'Renewal', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
       // Partner testPartner =GS_TestDataCreator.createPartner(testAccount1,'Reseller',testOpp);
        Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);
        Contract__c testContract = GS_TestDataCreator.createContract('test Contract', testAccount, 'Pending' , 'Shanghai', testContact, 'China' , 'Monthly' ,'Subscription Start Date', 'ZhongShan North Road', '30 Days');  
        Attachment testAttachment = GS_TestDataCreator.createAttachment(testContract, 'test Attachment', false , 'Test Contents');
        OpportunityContactRole testConRole = GS_TestDataCreator.createOppConRole(testContact, testOpp, 'Business User');
        
        Product2 testProduct = GS_TestDataCreator.createProduct('TestProduct1', true, true, 'implementation', 'ACV');
        PricebookEntry testPBEntry = GS_TestDataCreator.createPriceBookEntry(testProduct, 100);
       //Uday 24062016: Changed the Pass Through parameter as zero, as there is a new validation to have zero or null for cancelled opportunity products
        oppLineItem = GS_TestDataCreator.createOppLineItem(testPBEntry, testOpp, 'Renewal', 100, 200, 0, 'Yes', 'Analec','Renewed',10000, null, 'ACV', 'NA');
        
        testContract.Status__c = 'Customer Executed';
        testContract.Evergreen__c = 'No';
        testContract.Customer_Signed_Date__c = Date.valueOf('2015-10-20');
        update testContract;
        Test.stopTest();

        oppLineItem.No_of_Users__c = 100;
        oppLineItem.Data_Region__c = 'APAC';
        oppLineItem.Dataset__c = 'Contacts';
        oppLineItem.Site_License__c = 'APAC';
        oppLineItem.Subscription_Start_Date__c = Date.valueOf('2015-09-15');
        oppLineItem.Subscription_End_Date__c = Date.valueOf('2015-09-30');
        oppLineItem.Term_Months__c = 0;
        oppLineItem.Estimated_Completion_Date__c = Date.Today().addDays(5);
        oppLineItem.Renewal_Increase__c = 20;
        oppLineItem.ACpV__c = 0;
        oppLineItem.UnitPrice = 0;
        //oppLineItem.Work_Order__r = testWO1;
        oppLineItem.Status__c = 'Renewed';
        oppLineItem.Lost_Cancelled_Reason__c = 'Test Reason';
        oppLineItem.Cancel_Comment__c = 'Test Reason';
        update oppLineItem;
    
        testOpp.Non_Subsidized_Contracted_Value__c = 100000;
        testOpp.LOB__c = 'Equity - Research, Sales & Trading';
        testOpp.StageName = GS_GlobalVariables.OPPCLOSEDWONVERIFIED;        
    	testOpp.Sales_Ops_Owner__c = testUser.Id;
    	testOpp.OwnerId = testUser.Id;
        testOpp.Contract__c = testContract.Id;
        GS_GlobalVariables.EXECUTED = false;
    }
    	oppLineItem.Estimated_Completion_Date__c = Date.valueOf('2015-09-30');
    	update oppLineItem;
     	System.runAs(testUser){   
        try{
                    update testOpp;      	                 
            }
            catch(Exception ex){
                GS_OpportunityClosedTHandler CWT = new GS_OpportunityClosedTHandler();
                CWT.processException(ex);
            }
         }
     }
	
}