QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Net_New_Business__c</fullName>
        <inlineHelpText>Roll up of Net New Business from Opportunity Product(s).  Also (ACV - Annual Pass Through) - (Prior Year ACV - Prior Year Pass Through).</inlineHelpText>
        <label>Net New Business</label>
        <summarizedField>OpportunityLineItem.Net_New_Business__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prior_Year_Pass_Through__c</fullName>
        <inlineHelpText>Roll up of Prior Year Pass Through from Opportunity Product(s).</inlineHelpText>
        <label>Prior Year Pass Through</label>
        <summarizedField>OpportunityLineItem.Prior_Year_Pass_Through__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Status__c</field>
            <operation>notEqual</operation>
            <value>Lost</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewals</businessProcess>
        <description>Use this if there are one or more ACV renewal products on your opportunity.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ACpV__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Annual Contracted Product Value - the Product level breakout for Annual Contracted Value (ACV).</inlineHelpText>
        <label>ACpV</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cancel_Comment__c</fullName>
        <inlineHelpText>Required if product is Lost/Cancelled/Downtick</inlineHelpText>
        <label>Lost/Cancelled/Downtick Comment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lost_Cancelled_Reason__c</fullName>
        <inlineHelpText>Required when Opportunity Product &quot;Status&quot; is Lost or is Cancelled. Or If Revenue Delta Type is Downtick. If the Lost/Cancelled Reason indicates the business was lost to a competitor or incumbent, field Competitor/Incumbent is also required.</inlineHelpText>
        <label>Lost/Cancelled/Downtick Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget (No Competitor)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Uncertainty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor (Functionality)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor (Functionality + Price)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor (Price)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Nothing (Functionality)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Nothing (Functionality + Price)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Nothing (Price)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fewer Users</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ipreo Decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merger &amp; Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Reallocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidy Loss (No Competitor)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Resource</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Net_New_Business__c</fullName>
        <description>(Renewals only)
Delta between current revenue and previous revenue
Calculated.</description>
        <inlineHelpText>Read only, formula field:  (ACpV - Annual Pass Through) - (Prior Year ACpV - Prior Year Pass Through).</inlineHelpText>
        <label>Net New Business</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Year_ACpV__c</fullName>
        <description>For use in renewal uptick calculation</description>
        <inlineHelpText>For New Business Opportunities, this is 0.  For renewals, it is populated by the system with the ACpV from the previous Opportunity.  Used in calculating Net New Business for the Opportunity Product.</inlineHelpText>
        <label>Prior Year ACpV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Year_Pass_Through__c</fullName>
        <inlineHelpText>For New Business Opportunities, this is 0.  For renewals, it is populated by the system with the Annual Pass Through from the previous Opportunity.  Used in calculating Net New Business for the Opportunity Product.</inlineHelpText>
        <label>Prior Year Pass Through</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The values of Won/Lost pertain to New Business opportunities and the values of Cancelled/Renewed pertain to Renewal opportunities.</description>
        <inlineHelpText>Required when Opportunity Stage is Closed%.  When Status has not been populated, most fields on page are not validated by system.  Once Status is populated (with either Won/Lost for New Business or Renewed/Cancelled for Renewals), the validations occur.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Product_Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_TestOppLineItemCalNetNewBiz.cls
/**************************************************************************************************
 * Name           : GS_TestOppLineItemCalNetNewBiz
 * Object         : OpportunityLineItem
 * Requirement    : STY-00149 -> STY-00201
 * Target         : Test GS_OppLineItemCalNetNewBizTHandler
 * Refer classes  : 
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-06
 * Modify History :
 **************************************************************************************************/
@isTest
private class GS_TestOppLineItemCalNetNewBiz {

    // IF Status IN ( null, "Won", "Renewed" ) THEN Net New Business = ACpV - Prior Year ACpV - Pass Through + Prior  Year Pass Through
    static testMethod void calNetNewBiz1() {

        Test.startTest();
        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
       try{
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Opportunity testOpp1 = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        
        // createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
        Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true,null,'Project',null);
        Product2 testProduct2 = GS_TestDataCreator.createProduct('TestProduct2', true, false,null,'Project',null);

        // createPriceBookEntry(Product2 product, Decimal unitPrice)
        PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);
        PricebookEntry testPBEntry2 = GS_TestDataCreator.createPriceBookEntry(testProduct2, 100);

        // createOppLineItem(PricebookEntry priceEntry, Opportunity opp, String productTransactionType, Decimal acpv, Decimal tcpv, Decimal passThrough)
        OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp1, 'New Business', 100, 200, 50, 'Yes', 'Analec', null, null, null, 'ACV', 'NA');  
        OpportunityLineItem oppLineItem3 = GS_TestDataCreator.createOppLineItem(testPBEntry2, testOpp1, 'New Business', 0, 0, null, 'Yes', 'Analec','Lost', NULL, 'Incumbent (Functionality)', 'ACV', 'NA',false);
        OpportunityLineItem oppLineItem6 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp1, 'New Business', 100, 200, 50, 'Yes', 'Analec','won', null, null, 'ACV', 'NA');
        oppLineItem3.Cancel_Comment__c = 'Competitor (Both)';
        insert oppLineItem3;
        Test.stopTest();
			
        List<OpportunityLineItem> lstTestOppLineItems = new List<OpportunityLineItem>();

        OpportunityLineItem oppLineItemResult11 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem1.Id];
        //System.assertEquals(50, oppLineItemResult11.Net_New_Business__c);
        OpportunityLineItem oppLineItemResult13 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem3.Id];
        //System.assertEquals(0, oppLineItemResult13.Net_New_Business__c);

        oppLineItem1.Status__c = 'won';
        oppLineItem1.Prior_Year_ACpV__c = 10;
        oppLineItem1.Prior_Year_Pass_Through__c =30;
        lstTestOppLineItems.add(oppLineItem1);

        oppLineItem6.Status__c = 'Lost';
        oppLineItem6.ACpV__c = 0;
        oppLineItem6.UnitPrice = 0;
        oppLineItem6.Lost_Cancelled_Reason__c = 'Competitor (Both)';
        oppLineItem6.Cancel_Comment__c = 'Competitor (Both)';
        lstTestOppLineItems.add(oppLineItem6);
        
        update lstTestOppLineItems;
        
        OpportunityLineItem oppLineItemResult21 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem1.Id];
        //System.assertEquals(70, oppLineItemResult21.Net_New_Business__c);

        OpportunityLineItem oppLineItemResult25 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem6.Id];
        //System.assertEquals(0, oppLineItemResult25.Net_New_Business__c);
		}
        catch(System.DmlException ex){
        	System.debug(ex.getMessage());
            System.assert(true,ex.getMessage().contains('ACpV must be greater than 0 when this product is lost'));
		}
    }

static testMethod void calNetNewBiz2() {
        Test.startTest();
        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Opportunity testOpp2 = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'Renewal', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        
        // createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
        Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true,null,'Subscription',null);
        Product2 testProduct2 = GS_TestDataCreator.createProduct('TestProduct2', true, false,null,'Subscription',null);

        // createPriceBookEntry(Product2 product, Decimal unitPrice)
        PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);
        PricebookEntry testPBEntry2 = GS_TestDataCreator.createPriceBookEntry(testProduct2, 100);

        // createOppLineItem(PricebookEntry priceEntry, Opportunity opp, String productTransactionType, Decimal acpv, Decimal tcpv, Decimal passThrough)
        
        OpportunityLineItem oppLineItem2 = GS_TestDataCreator.createOppLineItem(testPBEntry2, testOpp2, 'Renewal', 0, 0, null, 'Yes', 'Analec','Cancelled', NULL, 'Incumbent (Functionality)', 'ACV', 'NA',false);  
        oppLineItem2.Cancel_Comment__c = 'Competitor (Both)';  
        insert oppLineItem2;
        OpportunityLineItem oppLineItem4 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp2, 'Renewal', 50, 100, 25, 'Yes', 'Analec','Renewed', NULL, 'Incumbent (Functionality)', 'ACV', 'NA');
       //Uday 24062016: Changed the Pass Through parameter as zero, as there is a new validation to have zero or null for cancelled opportunity products
        OpportunityLineItem oppLineItem5 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp2, 'Renewal', 0, 0, 0, 'Yes', 'Analec','Cancelled', NULL, 'Incumbent (Functionality)', 'ACV', 'NA',false);
        oppLineItem5.Cancel_Comment__c = 'Competitor (Both)';  
        insert oppLineItem5;
        Test.stopTest();
        List<OpportunityLineItem> lstTestOppLineItems = new List<OpportunityLineItem>();

        OpportunityLineItem oppLineItemResult12 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem2.Id];
        //System.assertEquals(0, oppLineItemResult12.Net_New_Business__c);

        oppLineItem2.Prior_Year_Pass_Through__c = 10;
        lstTestOppLineItems.add(oppLineItem2);

        oppLineItem4.Prior_Year_Pass_Through__c = 10;
        lstTestOppLineItems.add(oppLineItem4);

        //oppLineItem5.Status__c = 'Cancelled';
        oppLineItem5.ACpV__c = 0;
        oppLineItem5.UnitPrice = 0;
        oppLineItem5.Prior_Year_ACpV__c = 10;
        oppLineItem5.Prior_Year_Pass_Through__c = 10;
        oppLineItem5.Lost_Cancelled_Reason__c = 'Competitor (Functionality)';        
        lstTestOppLineItems.add(oppLineItem5);
		System.debug('===Line Items=='+lstTestOppLineItems);
        update lstTestOppLineItems;

        OpportunityLineItem oppLineItemResult22 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem2.Id];
        //System.assertEquals(10, oppLineItemResult22.Net_New_Business__c);

        OpportunityLineItem oppLineItemResult23 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem4.Id];
        //System.assertEquals(35, oppLineItemResult23.Net_New_Business__c);

        OpportunityLineItem oppLineItemResult24 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem5.Id];
        //System.assertEquals(0, oppLineItemResult24.Net_New_Business__c);
        } 
    static testMethod void calNetNewBiz3() {

        Test.startTest();
        Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
       try{
        insert testSetting1;    
        insert testSetting2;

        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Opportunity testOpp1 = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        
        // createProduct(String name, Boolean isAsset, Boolean requiredPassThrough)
        Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true,null,'Project',null);
        Product2 testProduct2 = GS_TestDataCreator.createProduct('TestProduct2', true, false,null,'Project',null);

        // createPriceBookEntry(Product2 product, Decimal unitPrice)
        PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);
        PricebookEntry testPBEntry2 = GS_TestDataCreator.createPriceBookEntry(testProduct2, 100);

        // createOppLineItem(PricebookEntry priceEntry, Opportunity opp, String productTransactionType, Decimal acpv, Decimal tcpv, Decimal passThrough)
        OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp1, 'New Business', 100, 200, 50, 'Yes', 'Analec', null, null, null, 'ACV', 'NA');  
        OpportunityLineItem oppLineItem3 = GS_TestDataCreator.createOppLineItem(testPBEntry2, testOpp1, 'New Business', 0, 0, null, 'Yes', 'Analec','Lost', NULL, 'Incumbent (Functionality)', 'ACV', 'NA');
        OpportunityLineItem oppLineItem6 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp1, 'New Business', 100, 200, 50, 'Yes', 'Analec','won', null, null, 'ACV', 'NA');
        Test.stopTest();

        List<OpportunityLineItem> lstTestOppLineItems = new List<OpportunityLineItem>();

        OpportunityLineItem oppLineItemResult11 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem1.Id];
        //System.assertEquals(50, oppLineItemResult11.Net_New_Business__c);
        OpportunityLineItem oppLineItemResult13 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem3.Id];
        //System.assertEquals(0, oppLineItemResult13.Net_New_Business__c);

        oppLineItem1.Status__c = 'Won';
        oppLineItem1.Prior_Year_ACpV__c = 10;
        oppLineItem1.Prior_Year_Pass_Through__c =30;
        lstTestOppLineItems.add(oppLineItem1);

        oppLineItem6.Status__c = 'Lost';
        oppLineItem6.ACpV__c = 30;
        oppLineItem6.UnitPrice = 30;
        oppLineItem6.Lost_Cancelled_Reason__c = 'Competitor (Both)';
        oppLineItem6.Cancel_Comment__c = 'Competitor (Both)';
        lstTestOppLineItems.add(oppLineItem6);
        
        update lstTestOppLineItems;
        
        OpportunityLineItem oppLineItemResult21 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem1.Id];

        OpportunityLineItem oppLineItemResult25 = [select Id, Net_New_Business__c from OpportunityLineItem where Id =: oppLineItem6.Id];
        System.assertEquals(70, oppLineItemResult21.Net_New_Business__c);
           System.assertEquals(30, oppLineItemResult25.Net_New_Business__c);
        }
        catch(System.DmlException ex){
            System.debug(ex.getMessage());            
        }
    }    
}