QA_Ipreo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_of_Active_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</description>
        <inlineHelpText>The number of Active Assets is used to determine the Account &quot;Status&quot; value.</inlineHelpText>
        <label>No. of Active Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Sponsored_Assets__c</fullName>
        <label>No. of Active Sponsored Assets</label>
        <summaryFilterItems>
            <field>Sponsored_Asset__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Sponsored_Asset__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Active_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Active Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Assets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_All_Work_Orders__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of All Work Orders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Sponsored_Assets__c</fullName>
        <label>No. of Sponsored Assets</label>
        <summaryForeignKey>Sponsored_Asset__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Prospect: no current or previous products
Customer: has data or software with active term or project with completion date in past 12 months or future estimated completion date
Former Customer: had data or software but term exp or had proj over 12 mo ago</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Set Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live (Project Still Open)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Provisioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AccountWOBatch.cls
global class GS_AccountWOBatch implements Database.Batchable<sObject>, Database.Stateful {
	String query;
	String createdRows;
	
	global GS_AccountWOBatch(){
		this.query = 'SELECT Id,Name, Status__c, No_of_Active_Sponsored_Assets__c,No_of_Active_Work_Orders__c,No_of_Active_Assets__c,No_of_Sponsored_Assets__c,No_of_All_Work_Orders__c,No_of_All_Assets__c, '; 
        //this.query += '(SELECT Id, Active__c,Product__r.Name,Product__r.ProductCode FROM Work_Orders__r where Product__r.Revenue_Type__c = \'PROJ\')';
        this.query += '(SELECT Id, Active__c,Product__r.Name,Product__r.ProductCode,Product__r.Revenue_Type__c FROM Work_Orders__r)'; 
        this.query += ' FROM Account';
		createdRows = '';
	}
	
	global Database.queryLocator start(Database.BatchableContext bc){
		return Database.getQueryLocator(query);		
	}
	
	global void execute(Database.BatchableContext bc, List<Account> scope){
		createdRows += processAccounts(scope);
	}
	
	global void finish(Database.BatchableContext bc){
		createAndSendReport(createdRows);
	}
	
	private String processAccounts(List<Account> accounts){
		String rowData = '';
		Integer activeWONumber = 0;
        for (Account tempAccount : accounts) {
        	String Status = '';
		    for(Work_Order__c tempWO : tempAccount.Work_Orders__r) {
		        if(tempWO.Active__c == true && tempWO.Product__r.Revenue_Type__c == 'PROJ') {
		            activeWONumber ++ ;
		        }
    	}
    	if (tempAccount.No_of_Active_Sponsored_Assets__c == 0
			&& activeWONumber == 0
			&& tempAccount.No_of_Active_Assets__c == 0) {
					if (tempAccount.No_of_Sponsored_Assets__c == 0
						&& tempAccount.Work_Orders__r.size() == 0
						&& tempAccount.No_of_All_Assets__c == 0) {
						Status = GS_GlobalVariables.ACCSTATUSPROSPECT;
					}
					else
					{
						Status = GS_GlobalVariables.ACCSTATUSFORMERCLIENT;
					}
					
			}
			else {
					Status = GS_GlobalVariables.ACCSTATUSCLIENT;
				}
    	rowData += '<tr>';
    	rowData += '<td>'+tempAccount.Id +'</td>';
        rowData += '<td>'+tempAccount.Name +'</td>';
        rowData += '<td>'+activeWONumber +'</td>';
        rowData += '<td>'+tempAccount.Work_Orders__r.size() +'</td>';
        rowData += '<td>'+tempAccount.Status__c +'</td>';
        rowData += '<td>'+Status +'</td>';
        rowData += '</tr>';
		    activeWONumber = 0;
		}
		return rowData;
	}
	
	private String createTable(String createdRows)
	{
        string s = '<html> <head> <style> table { font-family: arial, sans-serif; border-collapse: collapse; width: 100%; }td, th { border: 1px solid #dddddd; text-align: left;padding: 8px; } </style> </head> <body><table>';
        s += createHeader();
        s += createdRows;
        s += '</table></body> </html>';
        return s;
    }
    
    private String createHeader(){
        string headerString = '';       
        headerString += '<tr><th>ID</th><th>Account Name</th><th># Active Proj Work Orders</th><th># All Work Orders</th><th>Status</th><th>New Status</th></tr>';      
        return headerString;
    }
    
    private void createAndSendReport(String rows)
    {
        string finalFileName = 'Account Report '+Datetime.now().format('dd-MMM-yy hh:mm:ss a')+'.xls';
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        Blob test = Blob.valueOf(createTable(rows));
        blob csvBlob = test;
        csvAttc.setFileName(finalFileName);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {'uday_bikkumalla@epam.com'};
        String subject ='Account Report_'+ Datetime.now().format();
        email.setSubject(subject);
        email.setTargetObjectID(UserInfo.getUserID());
        email.saveAsActivity = false;
        email.setToAddresses(toAddresses);
        email.setPlainTextBody(subject);
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }     

}