QA_Ipreo/src/objects/Alert_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Group_Email__c</fullName>
        <inlineHelpText>Alert group email address</inlineHelpText>
        <label>Group Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <inlineHelpText>Alert group name</inlineHelpText>
        <label>Group Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Alert Groups</label>
</CustomObject>

QA_Ipreo/src/objects/Heat_Map_Cleanup_Duration_Criteria__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting to define number of days after which a heat map report should be deleted from system</description>
    <label>Heat Map Cleanup Duration Criteria</label>
</CustomObject>

QA_Ipreo/src/objects/Products_For_Corporate_Heat_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom setting is for storing the list of products to be included as part of the Corporate Heat Map report.</description>
    <label>Products For Corporate Heat Map</label>
</CustomObject>

QA_Ipreo/src/objects/User_List_Data_Update_Notifications__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of Users to be notified when specific data updates are done in the system. For example when the field Is Close Date In Current Year is updated by the respective yearly job.</description>
    <label>User List For Data Update Notifications</label>
</CustomObject>

QA_Ipreo/src/classes/GS_CustomSettingDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_CustomSettingDMLHandler
 * Object         : Custom Settings
 * Requirement    : 
 * Target         : DML on Custom Settings
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-09-24
 * Modify History :
 **************************************************************************************************/
public with sharing class GS_CustomSettingDMLHandler {
    
    // Get Alert Groups by names
    public static List<Alert_Groups__c> getAlertGroupsByNames(Set<String> groupNames) {
        return [SELECT Group_Email__c
                      ,Group_Name__c
                FROM Alert_Groups__c
                WHERE Group_Name__c =: groupNames];
    }
    
    public static List<Products_For_Corporate_Heat_Map__c> getProductsForHeatMap()
    {
        return Products_For_Corporate_Heat_Map__c.getAll().values();
    }
    
    public static User_List_Data_Update_Notifications__c getCustomSetting(string settingName)
    {
        User_List_Data_Update_Notifications__c notifSetting = User_List_Data_Update_Notifications__c.getValues(settingName);
        
        return notifSetting;
    }
    
    public static Heat_Map_Cleanup_Duration_Criteria__c getHeatMapCustomSetting(string settingName)
    {
        Heat_Map_Cleanup_Duration_Criteria__c heatMapSetting = Heat_Map_Cleanup_Duration_Criteria__c.getValues(settingName);
        system.debug('heatMapSetting---->>'+heatMapSetting);
        return heatMapSetting;
    }
}