QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Reason_for_RAG_Status__c</fullName>
        <label>Reason for RAG Status</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset associated with Opportunity</description>
        <label>Asset</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Asset.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Asset.Product2Id</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_RAG_Status__c</fullName>
        <formula>Asset__r.Reason_for_RAG_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reason for RAG Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_OppLineItemDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_OppLineItemDMLHandler
 * Object         : Asset/Opp Product
 *Requirement    : SPS-1082
 * Target         : Opporutnity DML Handler
 * Refer classes  :
 * Author         : Uday Bikkumalla
 * Create Date    : 2015-08-03
 * Modify History :
 **************************************************************************************************/
public class GS_OppLineItemDMLHandler {
  /* public static List<OpportunityLineItem> getLineItemsByAssets(List<Asset> assets) {
        return [SELECT id
                ,Name
                ,Reason_for_RAG_Status__c
                ,Asset__r.Reason_for_RAG_Status__c
                FROM OpportunityLineItem
                WHERE Asset__c in: assets   
               ];
    }*/
}