QA_Ipreo/src/objects/Asset_License__c.object
<CustomObject>
    <fields>
        <fullName>Active_Need_to_Be_Updated__c</fullName>
        <formula>OR(
    AND(
         Auto_Populated_Active_Status__c = true
        , NOT(ISPICKVAL(Status__c, &apos;Active&apos;))
       )
   ,AND(
         Auto_Populated_Active_Status__c = false
        , NOT(ISPICKVAL(Status__c, &apos;Inactive&apos;))
       )
)</formula>
        <label>Active Need to Be Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Populated_Active_Status__c</fullName>
        <formula>AND(
      Start_Date__c &lt;= DATEVALUE(NOW())
     ,End_Date__c &gt;= DATEVALUE(NOW())
)</formula>
        <label>Auto Populated Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_LicenseUpdateActiveStatusHandler.cls
/**************************************************************************************************
 * Name           : GS_LicenseUpdateActiveStatusHandler
 * Object         : License
 * Requirement    : STY-00012
 * Target         : A formula field Auto_Populated_Active_Status__c has been created to check license status. This class will update another field
 *                  align the formula field.
 * Refer classes  : 
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-03
 * Modify History :
 **************************************************************************************************/
public class GS_LicenseUpdateActiveStatusHandler {
    public static void updateStatus() {

		List<Asset_License__c> listLicense;
		List<Asset_License__c> listTargetLicense;

		listTargetLicense = new List<Asset_License__c>();
		listLicense = [SELECT Id
			                ,Status__c
			                ,Auto_Populated_Active_Status__c
			          FROM Asset_License__c
			          WHERE Active_Need_to_Be_Updated__c = true
			          Limit 3000];

		for(Asset_License__c tempLicense : listLicense) {
			tempLicense.Status__c = tempLicense.Auto_Populated_Active_Status__c ? 'Active' : 'Inactive';
			listTargetLicense.add(tempLicense);
		}

		update listTargetLicense;
	}
}