QA_Ipreo/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Reason_for_RAG_Status__c</fullName>
        <label>Reason for RAG Status</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset associated with Opportunity</description>
        <label>Asset</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Asset.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Asset.Product2Id</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_RAG_Status__c</fullName>
        <formula>Asset__r.Reason_for_RAG_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reason for RAG Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_OppLineItemAssetReasonTHandler.cls
/**************************************************************************************************
 * Name           : GS_OppLineItemAssetReasonTHandler
 * Object         : OpportunityLineItem/Asset
 * Requirement    : 
 * Target         : Update RAG Reason when asset is changed on Opportunity Product
 * Refer classes  : 
 * Author         : Uday Bikkumalla
 * Create Date    : 2016-08-03
 * Modify History :
 **************************************************************************************************/
public class GS_OppLineItemAssetReasonTHandler implements GS_Triggers.Handler{
 public void handle(){
 }
   /* public void handle(){
        List<OpportunityLineItem> lstOppProducts = new List<OpportunityLineItem>();
        Set<Id> assetIds = new Set<Id>();
        if(Trigger.isUpdate){
             for (Id tempId : Trigger.newMap.keySet()){                
                if(((OpportunityLineItem)Trigger.oldMap.get(tempId)).Asset__c != ((OpportunityLineItem)Trigger.newMap.get(tempId)).Asset__c){
                    System.debug('In side Update');
                    lstOppProducts.add(((OpportunityLineItem)Trigger.newMap.get(tempId)));
                    assetIds.add(((OpportunityLineItem)Trigger.newMap.get(tempId)).Asset__c);
                }
            }
            updateOppProductReason(assetIds, lstOppProducts);
        }
    }
    private void updateOppProductReason(Set<Id> assetIds, List<OpportunityLineItem> lstOppProducts){
        System.debug('Updating products'+assetIds);
        Map<Id,Asset> mapAssets = new Map<Id, Asset>([Select id, Reason_for_RAG_Status__c from Asset where id in : assetIds ]);
        for(OpportunityLineItem oli : lstOppProducts){
            if(oli.Asset__c != null && mapAssets.get(oli.Asset__c) != null){
                System.debug('inside update --'+oli.Asset__c);
                System.debug('inside update -ref-'+mapAssets.get(oli.Asset__c));
                System.debug('Updating products inside for'+mapAssets.get(oli.Asset__c).Reason_for_RAG_Status__c);
                oli.Reason_for_RAG_Status__c = mapAssets.get(oli.Asset__c).Reason_for_RAG_Status__c;}
            else
                oli.Reason_for_RAG_Status__c = '';            
        }
       /* try{
            update lstOppProducts;
        }
        catch(System.DmlException ex){
            throw ex;
        }
    }  
     */ 
}