QA_Ipreo/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>First_Response_Provided__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Response Provided</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A user may populate this field (usually from the Opportunity Cases related list) for scenarios like trial access, which requires internal setup.</description>
        <inlineHelpText>Opportunity that lead to this case</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Set-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activate User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On Users Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad hoc/management reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Coverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact / activity import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivate User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Bounceback or Auto Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure Alerts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feeds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware/Software Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation Request/Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IssueNet Deal Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Known Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Localization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial Access Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestCase.cls
@isTest
private class GS_TestCase {

	static testMethod void caseOne() {
    	
    	Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
    	Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
    	testSetting1.Name = 'Opportunity';
    	testSetting2.Name = 'OpportunityTeam';
    	testSetting1.isOpen__c = true;
    	testSetting2.isOpen__c = true;
    	insert testSetting1;	
    	insert testSetting2;

    	Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
		Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
		Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);

	    Case testCase = new Case();
	    testCase.AccountId = testAccount.Id;
	    testCase.Opportunity__c = testOpp.Id;
	    testCase.ContactId = testContact.Id;
	    testCase.Status = 'New';
	    testCase.Priority = '2 - Medium';
	    testCase.Origin = 'Direct Email';
	    testCase.Type = 'Service Request';
	    testCase.Subject = 'Test Case Subject';
	    testcase.Description = 'Test Case Description';
	    insert testCase;

	    testCase.First_Response_Provided__c = true;
	    update testCase;
	}

	static testMethod void caseTwo() {
    	
    	Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
    	Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
    	testSetting1.Name = 'Opportunity';
    	testSetting2.Name = 'OpportunityTeam';
    	testSetting1.isOpen__c = true;
    	testSetting2.isOpen__c = true;
    	insert testSetting1;	
    	insert testSetting2;

    	Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
		Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
		Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);

	    Case testCase = new Case();
	    testCase.AccountId = testAccount.Id;
	    testCase.Opportunity__c = testOpp.Id;
	    testCase.ContactId = testContact.Id;
	    testCase.Status = 'New';
	    testCase.Priority = '2 - Medium';
	    testCase.Origin = 'Direct Email';
	    testCase.Type = 'Service Request';
	    testCase.Subject = 'Test Case Subject';
	    testcase.Description = 'Test Case Description';
	    testCase.Sub_Type__c = 'Trial Access Request';
	    testcase.Trial_Start_Date__c = Datetime.now().date();
	    testCase.Trial_End_Date__c = Datetime.now().date().addDays(1);
	    insert testCase;
	}
}