QA_Ipreo/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>First_Response_Provided__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Response Provided</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Responded_by_Email_But_Not_Taken_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check when the email is replied by the service user, if someone has taken this owner of the case from a queue, check on, if not check off.</description>
        <label>Responded by Email But Not Taken Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Set-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activate User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On Users Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad hoc/management reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Coverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact / activity import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivate User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Bounceback or Auto Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure Alerts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feeds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware/Software Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation Request/Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IssueNet Deal Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Known Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Localization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_CaseAssignValueTHandler.cls
/**************************************************************************************************
 * Name           : GS_CaseAssignValueTHandler
 * Object         : Case
 * Requirement    :
 * Target         : assign value
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2016-12-4
 * Modify History :
 **************************************************************************************************/
public class GS_CaseAssignValueTHandler implements GS_Triggers.Handler {
	public void handle() {

		if (Trigger.isInsert && Trigger.isBefore) {
			System.debug(LoggingLevel.INFO, '*** GS_CaseAssignValueTHandler is executed: ');
			assginTypeAndSubType();
		}

		if (Trigger.isUpdate && Trigger.isBefore) {
			System.debug(LoggingLevel.INFO, '*** GS_CaseAssignValueTHandler is executed: ');
			checkIfCaseRespondedWithoutAssignToUser();
		}
	}

	// If email subject contains "Ipreo Identity Verification"
	// then default the Case Type to "Access Management" and the Sub Type to "Machine Registration".
	private void assginTypeAndSubType() {

		// Check the subject from emailmessage
		for (Case cs : (List<Case>)Trigger.new) {
			if (cs.Origin != NULL && cs.Subject != NULL) {
				String strSubject = cs.Subject.toLowerCase();
				if (		cs.Origin.contains('Email2Case')
				            &&	strSubject.contains('ipreo identity verification')) {
					cs.Type = 'Access Management';
					cs.Sub_Type__c = 'Machine Registration';
				}
			}

		}

	}

	// Check on Responded_by_Email_But_Not_Taken_Owner__c when the case is first responded manually withou
	// assign to some one from a queue.
	private void checkIfCaseRespondedWithoutAssignToUser() {
		for (Case cs : (List<Case>)Trigger.new) {
			System.debug(LoggingLevel.INFO, '*** cs.OwnerId: ' + cs.OwnerId);
			System.debug(LoggingLevel.INFO, '*** cs.Responded_by_Email_But_Not_Taken_Owner__c: ' + cs.Responded_by_Email_But_Not_Taken_Owner__c);
			System.debug(LoggingLevel.INFO, '*** cs.First_Response_Provided__c: ' + cs.First_Response_Provided__c);
			if (((Case)Trigger.oldMap.get(cs.Id)).First_Response_Provided__c != cs.First_Response_Provided__c && 
				cs.OwnerId != NULL && String.valueOf(cs.OwnerId).startsWith('00G') &&
				cs.Responded_by_Email_But_Not_Taken_Owner__c == FALSE &&
				cs.First_Response_Provided__c == TRUE) {
				cs.Responded_by_Email_But_Not_Taken_Owner__c = TRUE;
			}
		}
	}
}