QA_Ipreo/src/objects/Contract__c.object
<CustomObject>
    <description>Used instead of the standard Contract object to allow queues.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ACpV__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Annual Contracted Product Value - the Product level breakout for Annual Contracted Value (ACV).</inlineHelpText>
        <label>ACpV</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Pass_Through__c</fullName>
        <inlineHelpText>For products where part of the amount paid by the customer is &quot;passed through&quot; to a third party, such as Factset Workstation, this is the portion of the ACpV (current year amount) that is passed through and not kept by Ipreo.</inlineHelpText>
        <label>Annual Pass Through</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Year_ACpV__c</fullName>
        <description>For use in renewal uptick calculation</description>
        <inlineHelpText>For New Business Opportunities, this is 0.  For renewals, it is populated by the system with the ACpV from the previous Opportunity.  Used in calculating Net New Business for the Opportunity Product.</inlineHelpText>
        <label>Prior Year ACpV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <inlineHelpText>Defaults from Region of Opportunity Owner.  Can be changed.</inlineHelpText>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Vertical__c</fullName>
        <label>Product Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facilitates Opportunity Product.Asset lookup filter. Maintained through trigger.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Partner__c</fullName>
        <inlineHelpText>Partner that recommended IPREO to the customer.</inlineHelpText>
        <label>Levered Sale</label>
        <picklist>
            <picklistValues>
                <fullName>Arbor Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artemis IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackstone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunswick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christensen IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citigate DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Hill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continental Stock Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daiwa IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deutsche DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldman Sachs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iridium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPM DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Eye</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mitsubishi Securities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nomura IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4 Websystems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Santander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore Stock Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMTB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SNL Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solebury IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takara Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSTA (Tokyo Stock Transfer Agent)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <description>Opportunity Term in Months</description>
        <inlineHelpText>Term of subscription, INCLUSIVE of any free period.  Leave blank for non-subscription products.  If entered, Subscription Start Date and Subscription End Date must also be entered.</inlineHelpText>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>ACpV__c</fullName>
        <description>ACpV</description>
        <label>ACpV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Pass_Through__c</fullName>
        <label>Annual Pass Through</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated contract</description>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Est_Annual_Transaction_Fees__c</fullName>
        <label>Est. Annual Transaction Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Completion_Date__c</fullName>
        <label>Est. Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prior_Year_ACpV__c</fullName>
        <label>Prior Year ACpV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Region__c</fullName>
        <label>Product Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Vertical__c</fullName>
        <label>Product Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Capital Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS&amp;T</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TCpV__c</fullName>
        <label>TCpV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_WorkOrderDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_WorkOrderDMLHandler
 * Object         : Work_Order__c
 * Requirement    : 
 * Target         : DML on Work_Order__c
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-15
 * Modify History :
 **************************************************************************************************/
public class GS_WorkOrderDMLHandler {

	public static List<Work_Order__c> getWorkOrdersByOpportunityId(Set<Id> OpportunityIds) {
		return [SELECT Name
					  ,Opportunity__c
					  ,OwnerId
					  ,Account__c
					  ,Product__c
					  ,Contract__c
					  ,Est_Completion_Date__c
					  ,Opportunity_Product_Est_Completion_Date__c
					  ,ACpV__c
					  ,Prior_Year_ACpV__c
					  ,TCpV__c
					  ,Annual_Pass_Through__c
					  ,Est_Annual_Transaction_Fees__c
					  ,Term_Months__c
					  ,Product_Vertical__c
					  ,Product_Region__c
					  ,Referral_Partner__c
					  ,RecordTypeId
					  ,Sales_Rep__c
					  ,Product_Revenue_Type__c
					  ,Net_New_Business__c
					  ,Subscription_Start_Date__c
					  ,Subscription_End_Date__c
				FROM Work_Order__c
				WHERE Opportunity__c =: OpportunityIds];
	}

    // get Queue Id for each product, key is queue name and value is queue id
    // Since every productlineitem has a product so input in a list of opportunityLineItem
    public static Map<String, Id> getWOQueueNameWithQueueId(List<OpportunityLineItem> lstOpportunityLineItem) {

        Set<String> stQueueName = new Set<String>();
        // key is queue name and value is queue id
        Map<String, Id> mapQueue = new Map<String, Id>();

        // Get all selected queues
        for(OpportunityLineItem temp : lstOpportunityLineItem) {
            if(!stQueueName.contains(temp.Product2.Work_Order_Queue__c)){
                stQueueName.add(temp.Product2.Work_Order_Queue__c);
            }
        }

        for(QueueSobject tempQueueSobj : GS_GroupDMLHandler.getQueuesByObjNameAndQueueName(stQueueName, 'Work_Order__c')) {
            mapQueue.put(tempQueueSobj.Queue.Name, tempQueueSobj.QueueId);
        }

        return mapQueue;
    }
    
}