QA_Ipreo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Asset_Bundle__c</fullName>
        <description>This field is used to concatenate assets of the contact.</description>
        <label>Asset Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_ContactDmlHandler.cls
/**************************************************************************************************
 * Name           : GS_ContactDmlHandler
 * Object         : Contact
 * Requirement    : 
 * Target         : DML on Contact
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-10-16
 * Modify History :
 **************************************************************************************************/
public class GS_ContactDmlHandler {
    
    public static List<Contact> getContactsByConIds (Set<Id> conIds) {

    	return [SELECT Id
    				  ,Name
    				  ,AccountId
                      ,Asset_Bundle__c
                      ,GMG_Activity_Products__c
                      ,Corporate_Activity_Products__c
                      ,PCS_Activity_Products__c
    			FROM Contact
    			WHERE Id =: conIds];
    }

    public static List<Contact> getContactsWithAssetsByConIds (Set<Id> conIds) {

        return [SELECT Id
                      ,Name
                      ,AccountId
                      ,Asset_Bundle__c
                      ,(SELECT Id, Name, Active__c, Asset__r.Product2.ProductCode
                        FROM User_Assets__r)
                FROM Contact
                WHERE Id =: conIds];
    }
}