QA_Ipreo/src/objects/Follow_Rule_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>isOpen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isOpen</label>
        <type>Checkbox</type>
    </fields>
    <label>Follow Rule Setting</label>
</CustomObject>

QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_Close_Date_In_Current_Year__c</fullName>
        <label>Is Close Date In Current Year</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <inlineHelpText>Either Subscription (ACV and ACV/TRANS) or Project (PROJ).  Required to save the Opportunity.</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>New_Business</fullName>
        <active>true</active>
        <businessProcess>New Business and Renewals</businessProcess>
        <description>Use this if there are no ACV renewal products on your opportunity.</description>
        <label>New Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewals</businessProcess>
        <description>Use this if there are one or more ACV renewal products on your opportunity.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Revenue_Type__c</fullName>
        <description>Type of revenue associated with the opportunity product</description>
        <inlineHelpText>ACV:  Annual Contracted Value - subscription product.  PROJ:  Project.  ACV/TRANS:  Usage based product.  ACV/PROJ:  Project sold as part of a subscription.</inlineHelpText>
        <label>Product Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/User_List_Data_Update_Notifications__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of Users to be notified when specific data updates are done in the system. For example when the field Is Close Date In Current Year is updated by the respective yearly job.</description>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <label>Email Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User List For Data Update Notifications</label>
</CustomObject>

QA_Ipreo/src/classes/GS_TestUpdateYearDependentOppFieldsBatch.cls
@isTest
private class GS_TestUpdateYearDependentOppFieldsBatch {


    static testmethod void test() 
    {
    	Follow_Rule_Setting__c testSetting1 = new Follow_Rule_Setting__c();
        Follow_Rule_Setting__c testSetting2 = new Follow_Rule_Setting__c();
        testSetting1.Name = 'Opportunity';
        testSetting2.Name = 'OpportunityTeam';
        testSetting1.isOpen__c = true;
        testSetting2.isOpen__c = true;
        insert testSetting1;    
        insert testSetting2; 
        
        User_List_Data_Update_Notifications__c notif = new User_List_Data_Update_Notifications__c();
        notif.Name = 'UpdateYearDependentOppFieldsBatch';
        notif.Email_Addresses__c = 'test1@test.com,test2@test.com,test3@test.com';
        insert notif;
        
        User testUser1 = GS_TestDataCreator.createUser('Operations User', 'Tom.124@test.com', 'APAC');   
          
       	//insert oppourtunity and update the closedate 
        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');         
        Opportunity testOpp = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'New_Business', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        Contact testContact = GS_TestDataCreator.createContact('testA', testAccount);
        Product2 testProduct1 = GS_TestDataCreator.createProduct('TestProduct1', true, true, 'implementation', 'PROJ');  
        PricebookEntry testPBEntry1 = GS_TestDataCreator.createPriceBookEntry(testProduct1, 100);
        OpportunityLineItem oppLineItem1 = GS_TestDataCreator.createOppLineItem(testPBEntry1, testOpp, 'New Business', 100, 200, 50, 'Yes', 'Analec', null, 10000, null, 'PROJ', 'NA');
        system.debug('oppLineItem1 Oppline item type------->>>>'+oppLineItem1.Product_Revenue_Type__c);
        system.debug('Opp rev type------->>>>'+testOpp.Revenue_Type__c);
        testOpp.CloseDate=Date.valueOf(String.valueof(Datetime.now()));
        //testOpp.Is_Close_Date_In_Current_Year__c='No';
        testOpp.OwnerId= testUser1.Id;
        Update testOpp;
            
        //insert oppourtunity and update the closedate
        Account testAccount1 = GS_TestDataCreator.createAccount('TestAccount');
        Opportunity testOpp1 = GS_TestDataCreator.createOpportunity(testAccount, 'test opportunity', 'Renewal', 'Opportunity Identified', 'Subscription', '1 year', 'Tier 1');
        testOpp1.CloseDate=Date.valueOf(String.valueof(Datetime.now().addYears(-1)));
        testOpp1.OwnerId= testUser1.Id;
        Update testOpp1;

       	System.runAs(testUser1)
        { 
        	Test.startTest();
         	
         	//Update testOpp;
        	GS_UpdateYearDependentOppFieldsBatch rcb = new GS_UpdateYearDependentOppFieldsBatch();
        	Id batchId = Database.executeBatch(rcb);   
        	// after the testing stops, assert records were updated properly
        	System.assertEquals(2, [select count() from Opportunity Where (CloseDate = THIS_YEAR) or (CloseDate = LAST_YEAR)]);
            
            Test.stopTest();
    	}
        
   }    
    
}