QA_Ipreo/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>All_Managers__c</fullName>
        <label>All Managers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amended_File_Date__c</fullName>
        <description>EDD Integration</description>
        <label>Amended File Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bookrunners__c</fullName>
        <label>Bookrunners</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Status__c</fullName>
        <description>data migration - from Ian file</description>
        <label>Deal Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_IPO_Date__c</fullName>
        <label>Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exchange__c</fullName>
        <label>Exchange</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_File_Date__c</fullName>
        <description>EDD Integration</description>
        <label>Initial File Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ipreo_BDSF_1_10__BDCompanyId__c</fullName>
        <externalId>true</externalId>
        <label>BD Company Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Issue_Id__c</fullName>
        <description>EDD Integration</description>
        <externalId>true</externalId>
        <label>Issue Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <picklist>
            <controllingField>Mid_Industry__c</controllingField>
            <picklistValues>
                <fullName>Agricultural Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commodity Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diversified Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aluminum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrous Metals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold, Silver, and Precious Stones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-Ferrous Metals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car, Truck, and other Vehicle Manufacturers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car, Truck, and other Vehicle Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rubber and Plastics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Electronic Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durable Household Goods and Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Furnishings and Fixtures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photographic Equipment and Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreational Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sporting Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toys and Games</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing and Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footwear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Durable Household Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Textile Manufacturers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breweries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cigarettes and Other Tobacco Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distillers and Wineries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farm, Meat, and Dairy Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed and Packaged Foods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Drinks Manufacturers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Construction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mid_Industry__c</fullName>
        <label>Mid Industry</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metals and Mining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Durables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Non-Durables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food, Beverage, and Tobacco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homebuilding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Services and Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oil, Gas and Coal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewable Energy Equipment and Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology and Pharmaceuticals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare and Supplies Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerospace and Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conglomerates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Goods and Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials and Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Software and Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <description>EDD Integration</description>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>data migration - from Ian file</description>
        <label>Ticker</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>Buyside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sellside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_LeadInsertFromEDDHandler.cls
/**************************************************************************************************
 * Name           : GS_LeadInsertFromEDDHandler
 * Object         : Lead
 * Requirement    : 
 * Target         : Insert data which are got from EDD into Lead
 * Refer classes  :
 * Author         : Katherine Chen
 * Create Date    : 2016-04-05
 * Modify History :
 **************************************************************************************************/
public class GS_LeadInsertFromEDDHandler {

	public List<EDDEntity.errorMassage> insertLeadsData(list<EDDEntity.EDDLead> EDDEntityobj)
	{
		List<lead> getNewLeadList = new List<lead>();
		List<EDDEntity.errorMassage> errorMassageList = new List<EDDEntity.errorMassage>();
		Integer total = 0;
		Integer shoudInsertCount = 0;
		Integer convertSuccCount = 0;
		Integer insertErrorCount = 0;

		for(EDDEntity.EDDLead le : EDDEntityobj)
		{
			total ++;
			Lead newlead = new Lead();
			if(le.warehouse_id != null && String.valueOf(le.warehouse_id) !='0' )
			{
				List<lead> getExistLead = new List<lead>();
				getExistLead = [select Id , Name from Lead where Ipreo_BDSF_1_10__BDCompanyId__c = :(Decimal)le.warehouse_id];
				if(getExistLead.size() == 0)
				{
					shoudInsertCount ++;
					try
					{
						if (le.street_nm == null) le.street_nm = '';
						if (le.street_nm3 == null) le.street_nm3 = '';
						
						newlead.Ipreo_BDSF_1_10__BDCompanyId__c = (Decimal)le.warehouse_id;
						newlead.LastName = le.issuer_nm;
						newlead.Ticker__c = le.symbol;
						newlead.Exchange__c = le.exchange_nm;
						newlead.Industry = le.industry_macro_nm;
						newlead.Mid_Industry__c = le.industry_mid_nm;
						newlead.Micro_Industry__c = le.industry_nm;
						newlead.Street = le.street_nm + ' ' + le.street_nm3;
						newlead.State = le.province_nm;
						newlead.PostalCode = le.zip_cd;
						newlead.Country = le.country_nm;
						newlead.Phone = le.phone_no;
						newlead.Website = le.url;
						newlead.Deal_Status__c = le.deal_status_desc;
						newlead.Estimated_IPO_Date__c = le.expected_dt == null ? null: GS_LeadsUpdateFromEDDHandler.getDateFromJSON(le.expected_dt);
						newlead.Company = le.issuer_nm;
						newlead.CurrencyIsoCode = 'USD';
						newlead.Status = 'New';
						newlead.Issue_Id__c = (Decimal)le.issue_id;
						newlead.Status_Date__c = le.status_dt == null ? null: GS_LeadsUpdateFromEDDHandler.getDateFromJSON(le.status_dt);
						newlead.LeadSource = 'EDD';
						newlead.Amended_File_Date__c = le.amended_file_dt == null ? null: GS_LeadsUpdateFromEDDHandler.getDateFromJSON(le.amended_file_dt);
						newlead.Initial_File_Date__c = le.init_file_dt == null ? null: GS_LeadsUpdateFromEDDHandler.getDateFromJSON(le.init_file_dt);
						newlead.Bookrunners__c = le.Deal_bookrunners_parentCode;
						newlead.All_Managers__c = le.Deal_allmanagers_parentCode;
						newlead.Vertical__c = 'Corporate';

						getNewLeadList.add(newlead);
						convertSuccCount ++;
					}catch(Exception de)
					{
						EDDEntity.errorMassage em = new EDDEntity.errorMassage();
						em.warehouse_id = le.warehouse_id;
						em.lastName = le.issuer_nm;
						em.errorMass = de.getMessage();
						errorMassageList.add(em);
					}finally
					{
						continue;
					}
				}else
				{
					continue;
				}
			}else
			{
				EDDEntity.errorMassage em = new EDDEntity.errorMassage();
				em.warehouse_id = le.warehouse_id;
				em.lastName = le.issuer_nm;
				em.errorMass = 'Field warehouse_id is null.';
				errorMassageList.add(em);
			}
		}
			
		Database.Saveresult[] saveResult;
		saveResult = Database.insert(getNewLeadList, false);
		for(Integer i = 0; i<getNewLeadList.size(); i++)
		{
			Database.SaveResult s = saveResult[i];
			if(!s.isSuccess())
			{
				insertErrorCount ++;
				EDDEntity.errorMassage em = new EDDEntity.errorMassage();
				em.warehouse_id = Integer.valueOf(getNewLeadList[i].Ipreo_BDSF_1_10__BDCompanyId__c );
				em.lastName = getNewLeadList[i].LastName;
				em.errorMass = String.valueOf(s.getErrors()[0]);
				errorMassageList.add(em);
			}
			
		}

		System.debug('*** Total Count: ' + total );
		System.debug('*** Count of need to be inserted: ' + shoudInsertCount );
		System.debug('*** Count of converted successfully: ' + convertSuccCount );
		System.debug('*** Count of inserted successfully: ' + (convertSuccCount-insertErrorCount) );
		System.debug('*** errorMassageList: ' + errorMassageList );

		return errorMassageList;
	}
}