QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Bundle__c</fullName>
        <label>Product Bundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The values of Won/Lost pertain to New Business opportunities and the values of Cancelled/Renewed pertain to Renewal opportunities.</description>
        <inlineHelpText>Required when Opportunity Stage is Closed%.  When Status has not been populated, most fields on page are not validated by system.  Once Status is populated (with either Won/Lost for New Business or Renewed/Cancelled for Renewals), the validations occur.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Product_Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Subscription End Date must be same (coterminous) for all Opportunity Products on the Opportunity.  Req at Won, Renewed if Subscription Start Date and Term populated.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_OppLineItemUpdateOppValueTHander.cls
/**************************************************************************************************
 * Name           : GS_OppLineItemUpdateOppValueTHander
 * Object         : OpportunityLineItem
 * Requirement    :
 * Target         : Update Product_Bundled__c when line item is created, updated, deleted
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-16
 * Modify History :
 **************************************************************************************************/
public class GS_OppLineItemUpdateOppValueTHander implements GS_Triggers.Handler {
    
    public void handle() {
    	updateOppProCodeBundle();
    	updateOppRenewalDate();
    }

    private void updateOppProCodeBundle() {
    	Set<Id> setOppIds = new Set<Id>();
    	List<Opportunity> lstTargetOpp = new List<Opportunity>();
    	String strSeparator = '_';

    	if(Trigger.isUpdate){
	    	for(Id tempItemId : ((Map<Id,OpportunityLineItem>)Trigger.newMap).keySet()) {
	    		if(!setOppIds.contains(((Map<Id,OpportunityLineItem>)Trigger.newMap).get(tempItemId).OpportunityId)) {
	    			if(   ((Map<Id,OpportunityLineItem>)Trigger.newMap).get(tempItemId).Status__c
	    			   != ((Map<Id,OpportunityLineItem>)Trigger.oldMap).get(tempItemId).Status__c){
	    				setOppIds.add(((Map<Id,OpportunityLineItem>)Trigger.newMap).get(tempItemId).OpportunityId);
	    			}
	    		}
	    	}
	    } else if(Trigger.isDelete){
	    	for(OpportunityLineItem tempItem : (List<OpportunityLineItem>)Trigger.old) {
	    		if(!setOppIds.contains(tempItem.OpportunityId)) {
	    			setOppIds.add(tempItem.OpportunityId);
	    		}
	    	}
	    } else {
	    	for(OpportunityLineItem tempItem : (List<OpportunityLineItem>)Trigger.new) {
	    		if(!setOppIds.contains(tempItem.OpportunityId)) {
	    			setOppIds.add(tempItem.OpportunityId);
	    		}
	    	}
	    }

    	lstTargetOpp = GS_OpportunityDMLHandler.getOpportunitiesWithLineItemsById(setOppIds);

    	for (Opportunity tempOpp : lstTargetOpp) {
    		tempOpp.Product_Bundle__c = '';
    		for(Integer i = 0; i < tempOpp.OpportunityLineItems.size(); i++){
    			if(tempOpp.OpportunityLineItems[i].Status__c != GS_GlobalVariables.OPPLINEITEMSTATUSLOST && tempOpp.OpportunityLineItems[i].Status__c != GS_GlobalVariables.OPPLINEITEMSTATUSCANCELLED){
	    			if(i == 0) {
	    				tempOpp.Product_Bundle__c = tempOpp.OpportunityLineItems[i].ProductCode;
	    			} else if(String.isNotBlank(tempOpp.Product_Bundle__c)){
	    				tempOpp.Product_Bundle__c += strSeparator + tempOpp.OpportunityLineItems[i].ProductCode;
	    			} else{
	    				tempOpp.Product_Bundle__c = tempOpp.OpportunityLineItems[i].ProductCode;
	    			}
	    		}
    		}
    	}


    	try{
    		update lstTargetOpp;
    	}catch(DmlException ex) {
    		System.debug(LoggingLevel.Error, '*** Error Message: ' + ex.getMessage());
    	}
    }

    private void updateOppRenewalDate() {

    	if(Trigger.isupdate && Trigger.isAfter) {

    		Map<Id, Date> mapOppWithEndDate = new Map<Id, Date>();
	    	Map<Id, Opportunity> mapTargetOpp = new Map<Id, Opportunity>();
	    	Map<Id, OpportunityLineItem> mapNewLineItem = (Map<Id, OpportunityLineItem>)Trigger.newMap;
	    	Map<Id, OpportunityLineItem> oldNewLineItem = (Map<Id, OpportunityLineItem>)Trigger.oldMap;

	    	for(Id tempLineItemId : Trigger.newMap.keySet()) {
	    		if(    mapNewLineItem.get(tempLineItemId).Subscription_End_Date__c != NULL
	    			&& mapNewLineItem.get(tempLineItemId).Subscription_End_Date__c != oldNewLineItem.get(tempLineItemId).Subscription_End_Date__c) {
	    			mapOppWithEndDate.put(mapNewLineItem.get(tempLineItemId).OpportunityId, mapNewLineItem.get(tempLineItemId).Subscription_End_Date__c);
	    		}
	    	}

    		mapTargetOpp = new Map<Id, Opportunity>(GS_OpportunityDMLHandler.getOpportunitiesWithLineItemsById(mapOppWithEndDate.keySet()));

    		for(Id oppId : mapTargetOpp.keySet()) {
    			if(mapTargetOpp.get(oppId).RecordType.DeveloperName != GS_GlobalVariables.OPPRTNEWBUSINESS){
    				mapTargetOpp.remove(oppId);
    			}
    		}

    		for(Id oppId : mapTargetOpp.keySet()) {
    			mapTargetOpp.get(oppId).Renewal_Date__c = mapOppWithEndDate.get(oppId);
    		}

	    	try{
	    		if(!mapTargetOpp.isEmpty()){
	    			update mapTargetOpp.values();
	    		}
	    	}catch(DmlException ex) {
	    		System.debug(LoggingLevel.Error, '*** Error Message: ' + ex.getMessage());
	    	}
    	}
    }
}