QA_Ipreo/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>Applies to Opportunity Products sold as a subscription, only (N/A for projects).  Subscription End Date must be same (coterminous) for all Opportunity Products on the Opportunity.  Req at Won, Renewed if Subscription Start Date and Term populated.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_OpportunitySetRenewalDateHandler.cls
/**************************************************************************************************
 * Name           : GS_OpportunitySetRenewalDateHandler
 * Object         : Opportunity
 * Requirement    : 
 * Target         : Set RenewalDate value when opportunity status changed to "CWV"
 * Refer classes  :
 * Author         : Matthew Sun (matthew.sun@pwc.com)
 * Create Date    : 2016-02-26
 * Modify History :
 **************************************************************************************************/
public class GS_OpportunitySetRenewalDateHandler implements GS_Triggers.Handler{
    
    public void handle(){
    	Set<Id> oppIds = new Set<Id>();
    	Set<Opportunity> opps = new Set<Opportunity>();
            
        // Get opportunity id
        for(Opportunity opp : (List<Opportunity>)Trigger.new) {
    		if(opp.StageName == 'Closed Won Verified'){
            	oppIds.add(opp.Id);
            	opps.add(opp);
        	}
        }

        Map<Id, Date> mapOppDate = getOppLineItemsByOppIds(oppIds);

        for(Opportunity opp : opps){
            if(mapOppDate.get(opp.Id) != NULL){
        	   opp.Renewal_Date__c = mapOppDate.get(opp.Id).addDays(1);
            }
        }

    }

    public Map<Id, Date> getOppLineItemsByOppIds(Set<Id> oppIds){
    	List<OpportunityLineItem> oppItems = [SELECT Id, OpportunityId, Subscription_End_Date__c FROM OpportunityLineItem WHERE OpportunityId IN :oppIds];

    	Map<Id, Date> mapOppDate = new Map<Id, Date>();
    	for(OpportunityLineItem oppItem : oppItems){
    		if(oppItem.Subscription_End_Date__c != null && !mapOppDate.containsKey(oppItem.OpportunityId)){
    			mapOppDate.put(oppItem.OpportunityId, oppItem.Subscription_End_Date__c);
    		}
    	}

    	return mapOppDate;
    }

}