QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Sponsored_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If a value is placed in the Sponsored User Account field, the field should be true.</description>
        <label>Is Sponsored User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestSponsoredUserAssetsController.cls
@isTest
private class GS_TestSponsoredUserAssetsController {
    static testMethod void testMethod1() {
        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Contact testContact = GS_TestDataCreator.createContact('TestContact', testAccount);
        Product2 testProduct = GS_TestDataCreator.createProduct('TestProduct', true, false);
        Asset testAsset = GS_TestDataCreator.createAsset(testAccount, 'TestAsset', testProduct, 'NA');
        
        User_Asset__c testUserAsset = new User_Asset__c();
        testUserAsset.User__c = testContact.Id;
        testUserAsset.Asset__c = testAsset.Id;
        testUserAsset.Is_Sponsored_User__c = true;
        insert testUserAsset;

        ApexPages.StandardController stdAsset = new ApexPages.StandardController(testAsset);
        GS_SponsoredUserAssetsController controller = new GS_SponsoredUserAssetsController(stdAsset);

        System.assertEquals(1, controller.userAsset.size());
    }
}