QA_Ipreo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Data_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Region (AMER, EUR, APAC)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dataset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dataset (Contacts or Ownership)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pass_Through_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pass Through Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACV/TRANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seat_Fee_No_of_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Seat Fee (No. of Users)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_License_Per_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Where users are located and where we want to allocate the revenue.</description>
        <label>Site License (Per Region)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <picklist>
            <picklistValues>
                <fullName>GMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type_Default__c</fullName>
        <inlineHelpText>Determines the record type for the work order being created from this product.
If this value is blank, then no work order will be created.</inlineHelpText>
        <label>Work Order Type Default</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

QA_Ipreo/src/classes/GS_ProductDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_ProductDMLHandler
 * Object         : Prodcut
 * Requirement    : 
 * Target         : DML on Prodcut
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-10
 * Modify History :
 **************************************************************************************************/
public class GS_ProductDMLHandler {
    public static List<Product2> getProductsById(Set<Id> productIds) {
        System.debug(LoggingLevel.INFO, '*** executed GS_ProductDMLHandler.getProductsById');
        return [SELECT Id
                      , Name
                      , ProductCode
                      , Description
                      , RevenueScheduleType
                      , RevenueInstallmentPeriod
                      , NumberOfRevenueInstallments
                      , IsActive
                      , CreatedDate
                      , CreatedById
                      , LastModifiedDate
                      , LastModifiedById
                      , SystemModstamp
                      , Family
                      , IsDeleted
                      , Revenue_Type__c
                      , Vertical__c
                      , Pass_Through_Required__c
                      , Work_Order_Type_Default__c
                      , Site_License_Per_Region__c
                      , Seat_Fee_No_of_Users__c
                      , Dataset__c
                      , Data_Region__c
               FROM Product2
               WHERE Id in: productIds];
    }
    
    public static List<Product2> getAllProducts() 
    {
    	return [select id, Name from Product2 order by Name];	
    }
}