QA_Ipreo/src/objects/Sponsored_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sponsored Assets</relationshipLabel>
        <relationshipName>Sponsored_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Sponsored Accounts</relationshipLabel>
        <relationshipName>Sponsored_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsored Asset</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Sponsored Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_TestSponsoredAssetTrigger.cls
/**************************************************************************************************
 * Name           : GS_TestSponsoredAssetTrigger
 * Object         : 
 * Requirement    : 
 * Target         : Test handlers on SponsoredAssetTrigger
 * Refer classes  : 
 * Author         : Ambadas Joshi. M (ambadas_morkhandikar@epam.com)
 * Create Date    : 2016-06-08
 * Modify History :
 **************************************************************************************************/
@isTest
private class GS_TestSponsoredAssetTrigger {
    static  testMethod void checkDuplicateSponsoredAssets() {
        Account testAccount = GS_TestDataCreator.createAccount('TestAccount');
        Account testAccount1 = GS_TestDataCreator.createAccount('TestAccount1');
        Account testAccount2 = GS_TestDataCreator.createAccount('TestAccount2');
        Product2 testProduct = GS_TestDataCreator.createProduct('TestProduct', true, false);
        Asset testAsset = GS_TestDataCreator.createAsset(testAccount, 'TestAsset', testProduct, 'NA');
        
        createSponsoredAsset(testAsset, testAccount1);
        createSponsoredAsset(testAsset, testAccount2);
        
        try
        {
            createSponsoredAsset(testAsset, testAccount1);
        }
        catch(Exception ex)
        {
            system.assertEquals(ex.getMessage().contains(System.Label.Msg_Duplicate_Sponsored_Assets), true);
        }
    }
    
    private static Sponsored_Asset__c createSponsoredAsset(Asset asset, Account acc){
      Sponsored_Asset__c sAsset = new Sponsored_Asset__c();
      sAsset.Account_Name__c = acc.Id;
      sAsset.Asset_Name__c = asset.Id;
      sAsset.Active__c = true;
      insert sAsset;
      return sAsset;
    }
}