QA_Ipreo/src/objects/Sponsored_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Sponsored Accounts</relationshipLabel>
        <relationshipName>Sponsored_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsored Asset</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Sponsored Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_AssetDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_AssetDMLHandler
 * Object         : Asset
 * Requirement    : 
 * Target         : DML on Asset
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-07-06
 * Modify History :
 **************************************************************************************************/
public class GS_AssetDMLHandler {

    // Get Asset records and its associated user assets by Asset Ids
    public static List<Asset> getAssetsWithUserAssetsByIds(Set<Id> setAssetIds) {
    	return [SELECT Id
    				  ,Name
    				  ,Status
    				  ,(SELECT Id
    				  		 ,Name
    				  		 ,Active__c
    				  		 ,Asset__c
    				  		 ,User__c
    				   FROM User_Assets__r)
    			FROM Asset
    			WHERE Id in: setAssetIds];
    }

    // Get Asset records by Id
    public static List<Asset> getAssetsByIds(Set<Id> setAssetIds) {
        return [SELECT Id
                      ,Name
                      ,AccountId
                      ,Status
                FROM Asset
                WHERE Id in: setAssetIds];
    }


    // Get Sponsored Asset by Asset Id
    public static List<Asset> getSponAssetByAssetIds(Set<Id> setAssetIds) {
        return [SELECT Id
                      ,Name
                      ,Status
                      ,(SELECT Id
                              ,Active__c
                        FROM Sponsored_Accounts__r)
                FROM Asset
                WHERE Id in: setAssetIds];
    }
}