QA_Ipreo/src/objects/Sponsored_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sponsored Assets</relationshipLabel>
        <relationshipName>Sponsored_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Sponsored Accounts</relationshipLabel>
        <relationshipName>Sponsored_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsored Asset</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Sponsored Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_SponsoredAssetDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_SponsoredAssetDMLHandler
 * Object         : User Asset
 * Requirement    : 
 * Target         : DML on User Asset
 * Refer classes  :
 * Author         : Ambadas Joshi M <ambadas_morkhandikar@epam.com>
 * Create Date    : 2016-06-06
 * Modify History :
 **************************************************************************************************/

public class GS_SponsoredAssetDMLHandler {
	
	public static List<Sponsored_Asset__c> getSponsoredAssetsByAssetNames(Set<string> assetNames) {
		return [SELECT Id
					  ,Name
					  ,Asset_Name__c
					  ,Account_Name__c
					  ,Active__c
				FROM Sponsored_Asset__c
				WHERE Asset_Name__c in: assetNames
				LIMIT 9999];
	}

}