QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Sponsored_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If a value is placed in the Sponsored User Account field, the field should be true.</description>
        <label>Is Sponsored User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Denotes what role this contact plays in relation to the asset</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POC Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POC and User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_SponsoredUserAssetsController.cls
/**************************************************************************************************
 * Name           : GS_SponsoredUserAssetsController
 * Object         : Asset
 * Requirement    :
 * Target         : 
 * Refer classes  :
 * Author         : Matthew Sun (matthew.sun@pwc.com)
 * Create Date    : 2016-03-03
 * Modify History :
 **************************************************************************************************/
public class GS_SponsoredUserAssetsController{

    private Id assetId {get; set;}
    public List<User_Asset__c> userAsset {get;set;}

    public GS_SponsoredUserAssetsController(ApexPages.StandardController controller) {
        assetId = controller.getId();
        querySponsoredUserAssets();
    }

    public PageReference queryAllUserAssets(){
        queryUserAsset(false);
        return null;
    }

    public PageReference querySponsoredUserAssets(){
        queryUserAsset(true);
        return null;
    }
    
    public void queryUserAsset(Boolean isSponsoredUserAsset){
        String queryStr = 'SELECT Asset__r.Name, User__r.Account.Name, User__r.LastName, User__r.FirstName, Role__c, Active__c FROM User_Asset__c WHERE Asset__c = \''
                            + assetId + '\'';
        if(isSponsoredUserAsset){
            queryStr += ' AND Is_Sponsored_User__c = true';
        }
        System.debug('*************Start query************');
        System.debug(queryStr);

        userAsset = Database.query(queryStr);
    }

}