QA_Ipreo/src/objects/User_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Contact</description>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Assets</relationshipLabel>
        <relationshipName>User_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Asset</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>User Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_UserAssetDMLHandler.cls
/**************************************************************************************************
 * Name           : GS_UserAssetDMLHandler
 * Object         : User Asset
 * Requirement    : 
 * Target         : DML on User Asset
 * Refer classes  :
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-12-03
 * Modify History :
 **************************************************************************************************/
public class GS_UserAssetDMLHandler {
    
	public static List<User_Asset__c> getUserAssetsByAssetIds(Set<Id> assetIds) {
		return [SELECT Id
					  ,User__c
					  ,Asset__c
				FROM User_Asset__c
				WHERE Asset__c in: assetIds
				LIMIT 9999];
	}

}