QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Active_Need_to_Be_Updated__c</fullName>
        <formula>Auto_Populated_Active_Status__c !=  Active__c</formula>
        <label>Active Need to Be Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Populated_Active_Status__c</fullName>
        <formula>AND(
     RecordType.DeveloperName = &apos;Analytics&apos;
    ,OR( 
         AND( 
              NOT(ISBLANK(Completion_Date__c))
             ,YEAR(Completion_Date__c) = YEAR(DATEVALUE(NOW()))
            )
        ,AND(
              ISBLANK(Completion_Date__c)
             ,NOT(ISBLANK(Est_Completion_Date__c))
             ,Est_Completion_Date__c &gt; DATEVALUE(Now())
            )
       )
)</formula>
        <label>Auto Populated Active Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_WorkOrderUpdateActiveStatusHandler.cls
/**************************************************************************************************
 * Name           : GS_WorkOrderUpdateActiveStatusHandler
 * Object         : Work_Order
 * Requirement    : STY-00012
 * Target         : For each work order of record type “Research”, If Completion Date populated and year = current year,
 *                  active. Else If Completion Date not populated and Expected Completion Date populated and
 *                  Expected Completion Date year = current year, active Else, inactive.
 *                  A formula field has been created to follow the logic above. This class will update another field
 *                  align the formula field.
 * Refer classes  : 
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-03
 * Modify History :
 **************************************************************************************************/
public with sharing class GS_WorkOrderUpdateActiveStatusHandler {
    
	public static void updateActiveStatus() {
		System.debug(LoggingLevel.INFO, '*** : GS_WorkOrderUpdateActiveStatusHandler.updateActiveStatus is execueted.');
		List<Work_Order__c> listWO;
		List<Work_Order__c> listTargetWO;

		listTargetWO = new List<Work_Order__c>();
		listWO = [SELECT Id
			                ,Active__c
			                ,Auto_Populated_Active_Status__c
			          FROM Work_Order__c
			          WHERE Active_Need_to_Be_Updated__c = true
			          Limit 3000];

		for(Work_Order__c tempWO : listWO) {
			tempWO.Active__c = tempWO.Auto_Populated_Active_Status__c;
			listTargetWO.add(tempWO);
		}

		update listTargetWO;
	}
}