QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Populated_Active_Status__c</fullName>
        <formula>AND(
     RecordType.DeveloperName = &apos;Analytics&apos;
    ,OR( 
         AND( 
              NOT(ISBLANK(Completion_Date__c))
             ,YEAR(Completion_Date__c) = YEAR(DATEVALUE(NOW()))
            )
        ,AND(
              ISBLANK(Completion_Date__c)
             ,NOT(ISBLANK(Est_Completion_Date__c))
             ,Est_Completion_Date__c &gt; DATEVALUE(Now())
            )
       )
)</formula>
        <label>Auto Populated Active Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_UpdateActiveStatusSchedule.cls
/**************************************************************************************************
 * Name           : GS_UpdateActiveStatusSchedule
 * Object         : Work_Order__c
 * Requirement    : STY-00012
 * Target         : Update the Active field on Work Order and make it align with the field Auto_Populated_Active_Status__c
 * Refer classes  : GS_WorkOrderUpdateActiveStatusHandler
 * Author         : Xiao Yang (yang.xiao@cnsdc01.pwc.com)
 * Create Date    : 2015-06-03
 * Modify History :
 **************************************************************************************************/
global class GS_UpdateActiveStatusSchedule implements Schedulable {
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new GS_WorkOrderUpdateStatusBatch(), 200);
    }
}