QA_Ipreo/src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Active_Need_to_Be_Updated__c</fullName>
        <formula>Auto_Populated_Active_Status__c !=  Active__c</formula>
        <label>Active Need to Be Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field used to calculate the status of an account.  Logic associated with calculating account status counts the number of &quot;active&quot; work orders.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Populated_Active_Status__c</fullName>
        <formula>AND(
     RecordType.DeveloperName = &apos;Analytics&apos;
    ,OR( 
         AND( 
              NOT(ISBLANK(Completion_Date__c))
             ,YEAR(Completion_Date__c) = YEAR(DATEVALUE(NOW()))
            )
        ,AND(
              ISBLANK(Completion_Date__c)
             ,NOT(ISBLANK(Est_Completion_Date__c))
             ,Est_Completion_Date__c &gt; DATEVALUE(Now())
            )
       )
)</formula>
        <label>Auto Populated Active Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA_Ipreo/src/classes/GS_WorkOrderUpdateStatusBatch.cls
global class GS_WorkOrderUpdateStatusBatch implements Database.Batchable<sObject>, Database.Stateful {
    public String query;
    String strSaveErrResult = '';
    global GS_WorkOrderUpdateStatusBatch() {
        this.query = 'SELECT Id, Active__c, Auto_Populated_Active_Status__c FROM Work_Order__c WHERE Active_Need_to_Be_Updated__c = true Limit 9999';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Sobject> scope) {

        List<Work_Order__c> listTargetWO;
        listTargetWO = new List<Work_Order__c>();

        for(Work_Order__c tempWO : (List<Work_Order__c>)scope) {
            tempWO.Active__c = tempWO.Auto_Populated_Active_Status__c;
            listTargetWO.add(tempWO);
        }

        List<Database.SaveResult> saveResults = Database.update(listTargetWO, false);
        for(Database.SaveResult res : saveResults) {
            if(!res.isSuccess()) {
                for(Database.Error err : res.getErrors()) {
                    strSaveErrResult += err.getFields() + ': ' + err.getMessage() + '\n';
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

        if(String.isNotBlank(strSaveErrResult)) {
            GS_EmailUtility.Send(UserInfo.getUserId(), 'Account Status Calucation Exception on Work Order ' + String.valueOf(Datetime.now()), strSaveErrResult);
        }

        Database.executeBatch(new GS_LicenseUpdateStatusBatch(), 200);
    }
}